import type { ProjectTemplate } from "../types";

/**
 * 5 long-term career journeys. The ProjectTemplate Category type has no
 * separate "career" value, so these map to category: "work" — consistent
 * with how habits/work.ts already covers professional-domain content.
 */
export const careerProjects: ProjectTemplate[] = [
  {
    id: "project_basic_professional_discipline",
    title_ar: "مشروع الانضباط المهني الأساسي",
    title_en: "Basic Professional Discipline Project",
    description_ar: "رحلة 30 يومًا لبناء أساس انضباط مهني قوي: تخطيط، أولويات، وتركيز يومي",
    description_en: "A 30-day journey building a strong foundation of professional discipline: planning, priorities, and daily focus",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    durationDays: 30,
    dailyCommitmentMinutes: 20,
    milestones: [
      { day: 7, title_ar: "أسبوع من التخطيط اليومي المنتظم", title_en: "A week of consistent daily planning", reward: { xp: 30, badge: "بداية منضبطة" } },
      { day: 15, title_ar: "نصف الرحلة مع وضوح أكبر في الأولويات", title_en: "Halfway through with greater clarity in priorities", reward: { xp: 35, badge: "أولويات واضحة" } },
      { day: 23, title_ar: "التركيز اليومي أصبح عادة لا مجهودًا", title_en: "Daily focus has become habit, not effort", reward: { xp: 40, badge: "تركيز راسخ" } },
      { day: 30, title_ar: "ثلاثون يومًا من الانضباط المهني المتصاعد", title_en: "Thirty days of growing professional discipline", reward: { xp: 55, badge: "منضبط مهنيًا" } },
    ],
    finalReward: { xp: 140, badge: "🏅 صاحب الانضباط المهني الأساسي", title_ar: "المنضبط" },
    icon: "🎯",
    successStories: [
      "من التزم بتخطيط خمس دقائق يوميًا، وجد يومه أكثر وضوحًا وأقل تشتتًا",
      "الانضباط الصغير المتكرر بنى ثقة مهنية لم تبنها محاولات حماسية سابقة",
    ],
  },
  {
    id: "project_personal_brand_building",
    title_ar: "مشروع بناء العلامة الشخصية المهنية",
    title_en: "Professional Personal Brand Building Project",
    description_ar: "رحلة 60 يومًا لبناء سمعة مهنية واضحة وموثوقة في مجال تخصصك",
    description_en: "A 60-day journey building a clear, trusted professional reputation in your field",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    durationDays: 60,
    dailyCommitmentMinutes: 25,
    milestones: [
      { day: 15, title_ar: "هوية مهنية واضحة تم تحديدها", title_en: "A clear professional identity defined", reward: { xp: 40, badge: "هوية واضحة" } },
      { day: 30, title_ar: "نصف الرحلة مع حضور مهني متزايد", title_en: "Halfway through with growing professional presence", reward: { xp: 50, badge: "حضور متنامٍ" } },
      { day: 45, title_ar: "تفاعل حقيقي من الشبكة المهنية", title_en: "Genuine engagement from your professional network", reward: { xp: 55, badge: "تفاعل حقيقي" } },
      { day: 60, title_ar: "ستون يومًا من بناء سمعة مهنية متسقة", title_en: "Sixty days building a consistent professional reputation", reward: { xp: 70, badge: "سمعة راسخة" } },
    ],
    finalReward: { xp: 195, badge: "🏅 صاحب العلامة الشخصية المهنية", title_ar: "الموثوق" },
    icon: "🏷️",
    successStories: [
      "من نشر بانتظام في مجاله، بدأ يتلقى فرصًا لم تكن تصله من قبل",
      "الاتساق في الظهور المهني كان أهم من كمية المحتوى المنشور نفسها",
    ],
  },
  {
    id: "project_career_transition",
    title_ar: "مشروع الانتقال المهني",
    title_en: "Career Transition Project",
    description_ar: "رحلة 90 يومًا للتحضير المنظم للانتقال إلى مسار مهني جديد بثقة ووضوح",
    description_en: "A 90-day journey of organized preparation for transitioning to a new career path with confidence and clarity",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    durationDays: 90,
    dailyCommitmentMinutes: 35,
    milestones: [
      { day: 20, title_ar: "المسار الجديد ومتطلباته تم تحديدها بوضوح", title_en: "The new path and its requirements clearly defined", reward: { xp: 50, badge: "خريطة واضحة" } },
      { day: 45, title_ar: "نصف الرحلة مع مهارات جديدة قيد البناء", title_en: "Halfway through, with new skills under construction", reward: { xp: 60, badge: "مهارات ناشئة" } },
      { day: 70, title_ar: "أولى الفرص أو المقابلات في المسار الجديد", title_en: "First opportunities or interviews in the new path", reward: { xp: 65, badge: "أولى الخطوات" } },
      { day: 90, title_ar: "تسعون يومًا من التحضير المنظم للانتقال", title_en: "Ninety days of organized transition preparation", reward: { xp: 85, badge: "جاهز للانتقال" } },
    ],
    finalReward: { xp: 240, badge: "🏅 صاحب الانتقال المهني الناجح", title_ar: "المتحوّل" },
    icon: "🚪",
    successStories: [
      "من خطط لانتقاله على مراحل واضحة، تجنب القفزة العشوائية التي ندم عليها آخرون",
      "بناء المهارات الجديدة قبل ترك المسار القديم منحه أمانًا نفسيًا خلال التحول",
    ],
  },
  {
    id: "project_emerging_leadership",
    title_ar: "مشروع القيادة الناشئة",
    title_en: "Emerging Leadership Project",
    description_ar: "رحلة 60 يومًا لتطوير مهارات القيادة الأساسية: التفويض، التواصل، واتخاذ القرار",
    description_en: "A 60-day journey developing core leadership skills: delegation, communication, and decision-making",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    durationDays: 60,
    dailyCommitmentMinutes: 30,
    milestones: [
      { day: 15, title_ar: "أساسيات القيادة تم فهمها وتطبيقها", title_en: "Leadership fundamentals understood and applied", reward: { xp: 45, badge: "أساس قيادي" } },
      { day: 30, title_ar: "نصف الرحلة مع أول تفويض ناجح لمهمة", title_en: "Halfway through, with the first successful task delegation", reward: { xp: 55, badge: "تفويض ناجح" } },
      { day: 45, title_ar: "ثقة الفريق أو الزملاء تتزايد بوضوح", title_en: "Team or colleagues' trust clearly growing", reward: { xp: 60, badge: "ثقة متنامية" } },
      { day: 60, title_ar: "ستون يومًا من تطوير القيادة الناشئة", title_en: "Sixty days developing emerging leadership", reward: { xp: 75, badge: "قائد ناشئ" } },
    ],
    finalReward: { xp: 210, badge: "🏅 صاحب مهارات القيادة الناشئة", title_ar: "القائد الناشئ" },
    icon: "🧭",
    successStories: [
      "من تدرب على التفويض رغم صعوبته الأولى، وجد فريقه أكثر إنتاجية واستقلالية",
      "القرارات الصعبة أصبحت أسهل بعد أن بنى إطارًا واضحًا لاتخاذها",
    ],
  },
  {
    id: "project_first_entrepreneurial_steps",
    title_ar: "مشروع أولى خطوات ريادة الأعمال",
    title_en: "First Entrepreneurial Steps Project",
    description_ar: "رحلة 90 يومًا للانتقال من فكرة مشروع إلى أول نسخة حقيقية قابلة للاختبار في السوق",
    description_en: "A 90-day journey moving from a business idea to a first real, market-testable version",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    durationDays: 90,
    dailyCommitmentMinutes: 45,
    milestones: [
      { day: 20, title_ar: "الفكرة تم التحقق من جدواها الأولية", title_en: "The idea's initial feasibility validated", reward: { xp: 55, badge: "فكرة مُختبَرة" } },
      { day: 45, title_ar: "نصف الرحلة مع أول نموذج أولي جاهز", title_en: "Halfway through, with the first working prototype ready", reward: { xp: 70, badge: "نموذج أولي" } },
      { day: 70, title_ar: "أول عملاء أو مستخدمين حقيقيين للمشروع", title_en: "The first real customers or users for the project", reward: { xp: 80, badge: "أول عملاء" } },
      { day: 90, title_ar: "تسعون يومًا انتهت بمشروع حقيقي قابل للاختبار", title_en: "Ninety days culminating in a real, testable venture", reward: { xp: 100, badge: "رائد أعمال ناشئ" } },
    ],
    finalReward: { xp: 275, badge: "🏅 صاحب أولى خطوات ريادة الأعمال", title_ar: "الرائد" },
    icon: "🚀",
    successStories: [
      "من اختبر فكرته مبكرًا بدل الانتظار للكمال، وفّر أشهرًا كان سيهدرها في بناء ما لا يحتاجه أحد",
      "أول عميل حقيقي، مهما كان صغيرًا، غيّر نظرته لمشروعه من فكرة إلى واقع ملموس",
    ],
  },
];
