import type { ProjectTemplate } from "../types";

/**
 * 6 long-term learning journeys, spanning reading intensity, skill
 * mastery, personal knowledge systems, language acquisition, content
 * creation, and research contribution.
 */
export const learningProjects: ProjectTemplate[] = [
  {
    id: "project_intensive_reading",
    title_ar: "مشروع القراءة المكثفة",
    title_en: "Intensive Reading Project",
    description_ar: "رحلة 30 يومًا لبناء عادة قراءة يومية قوية وإنهاء عدة كتب بوتيرة ثابتة",
    description_en: "A 30-day journey to build a strong daily reading habit and finish several books at a steady pace",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    durationDays: 30,
    dailyCommitmentMinutes: 25,
    milestones: [
      { day: 7, title_ar: "أسبوع من القراءة اليومية المنتظمة", title_en: "A week of consistent daily reading", reward: { xp: 30, badge: "بداية القارئ" } },
      { day: 15, title_ar: "أول كتاب اكتمل خلال الرحلة", title_en: "The first book completed during the journey", reward: { xp: 40, badge: "أول إنجاز" } },
      { day: 23, title_ar: "القراءة أصبحت عادة يومية لا مجهودًا", title_en: "Reading has become a daily habit, not an effort", reward: { xp: 45, badge: "قارئ منتظم" } },
      { day: 30, title_ar: "ثلاثون يومًا من القراءة المكثفة", title_en: "Thirty days of intensive reading", reward: { xp: 55, badge: "قارئ مكثف" } },
    ],
    finalReward: { xp: 145, badge: "🏅 صاحب عادة القراءة المكثفة", title_ar: "القارئ" },
    icon: "📚",
    successStories: [
      "من التزم بعشرين دقيقة يوميًا فقط، أنهى ثلاثة كتب لم يكن يتخيل إنهاءها في شهر واحد",
      "الوتيرة الثابتة تفوقت على محاولات سابقة بدأت بكتاب ضخم توقف في منتصفه",
    ],
  },
  {
    id: "project_skill_mastery",
    title_ar: "مشروع إتقان مهارة جديدة",
    title_en: "New Skill Mastery Project",
    description_ar: "رحلة 60 يومًا للانتقال من مبتدئ إلى متمكّن حقيقي في مهارة عملية تختارها",
    description_en: "A 60-day journey moving from beginner to genuinely competent in a practical skill of your choosing",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    durationDays: 60,
    dailyCommitmentMinutes: 30,
    milestones: [
      { day: 15, title_ar: "أساسيات المهارة تم إتقانها", title_en: "The skill fundamentals mastered", reward: { xp: 40, badge: "أساس متين" } },
      { day: 30, title_ar: "نصف الرحلة مع تقدم عملي ملموس", title_en: "Halfway through with tangible practical progress", reward: { xp: 50, badge: "تقدم ملموس" } },
      { day: 45, title_ar: "المهارة تُمارَس بثقة متزايدة", title_en: "The skill is practiced with growing confidence", reward: { xp: 55, badge: "ثقة متنامية" } },
      { day: 60, title_ar: "ستون يومًا من التمرن المتواصل حتى الإتقان", title_en: "Sixty days of continuous practice toward mastery", reward: { xp: 70, badge: "متقن المهارة" } },
    ],
    finalReward: { xp: 195, badge: "🏅 صاحب مهارة متقنة جديدة", title_ar: "المتقن" },
    icon: "🛠️",
    successStories: [
      "من مارس المهارة يوميًا دون انقطاع، تفوق على من تعلمها بجلسات متباعدة لسنوات",
      "الثقة العملية جاءت بعد أسابيع من الممارسة الصامتة، لا من قراءة نظرية إضافية",
    ],
  },
  {
    id: "project_personal_knowledge_system",
    title_ar: "مشروع بناء نظام معرفي شخصي",
    title_en: "Building a Personal Knowledge System Project",
    description_ar: "رحلة 45 يومًا لبناء نظام رقمي متكامل يجمع كل ما تتعلمه بطريقة منظمة وقابلة للاسترجاع",
    description_en: "A 45-day journey building a comprehensive digital system that captures everything you learn in an organized, retrievable way",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    durationDays: 45,
    dailyCommitmentMinutes: 20,
    milestones: [
      { day: 10, title_ar: "هيكل النظام المعرفي تم تصميمه", title_en: "The knowledge system's structure designed", reward: { xp: 35, badge: "تصميم أولي" } },
      { day: 22, title_ar: "نصف الرحلة والنظام يمتلئ بمحتوى منظم", title_en: "Halfway through, the system filling with organized content", reward: { xp: 45, badge: "نظام حيّ" } },
      { day: 35, title_ar: "النظام أصبح مرجعًا يوميًا فعليًا", title_en: "The system has become an actual daily reference", reward: { xp: 50, badge: "مرجع فعّال" } },
      { day: 45, title_ar: "خمسة وأربعون يومًا من بناء نظام معرفي راسخ", title_en: "Forty-five days building a solid knowledge system", reward: { xp: 60, badge: "بانٍ للمعرفة" } },
    ],
    finalReward: { xp: 170, badge: "🏅 صاحب النظام المعرفي المتكامل", title_ar: "المنظِّم" },
    icon: "🧠",
    successStories: [
      "من بنى نظامه تدريجيًا، توقف عن نسيان أفكار كان يفقدها سابقًا بلا توثيق",
      "الرجوع لملاحظات قديمة منظمة، وفّر له وقتًا كان يهدره في إعادة التفكير من الصفر",
    ],
  },
  {
    id: "project_new_language_from_scratch",
    title_ar: "مشروع تعلم لغة جديدة من الصفر",
    title_en: "Learning a New Language From Scratch Project",
    description_ar: "رحلة 90 يومًا للانتقال من عدم معرفة اللغة إلى محادثة أساسية واثقة فيها",
    description_en: "A 90-day journey moving from no knowledge of the language to confident basic conversation",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    durationDays: 90,
    dailyCommitmentMinutes: 30,
    milestones: [
      { day: 20, title_ar: "المفردات والقواعد الأساسية تم إتقانها", title_en: "Basic vocabulary and grammar mastered", reward: { xp: 45, badge: "أساس لغوي" } },
      { day: 45, title_ar: "نصف الرحلة مع أول جملة كاملة بثقة", title_en: "Halfway through, with the first confident complete sentence", reward: { xp: 55, badge: "بداية الطلاقة" } },
      { day: 70, title_ar: "محادثة أساسية أصبحت ممكنة دون تردد كبير", title_en: "Basic conversation now possible without much hesitation", reward: { xp: 65, badge: "محادثة واثقة" } },
      { day: 90, title_ar: "تسعون يومًا من الصفر حتى المحادثة الأساسية", title_en: "Ninety days from zero to basic conversation", reward: { xp: 85, badge: "متحدث ناشئ" } },
    ],
    finalReward: { xp: 235, badge: "🏅 صاحب لغة جديدة من الصفر", title_ar: "متعدد اللغات" },
    icon: "🌍",
    successStories: [
      "من مارس ثلاثين دقيقة يوميًا بلا انقطاع، تفاجأ بقدرته على محادثة بسيطة خلال ثلاثة أشهر فقط",
      "الانتظام اليومي القصير تفوق على محاولات سابقة بجلسات طويلة متباعدة انتهت بالتوقف",
    ],
  },
  {
    id: "project_writing_and_publishing",
    title_ar: "مشروع الكتابة والنشر",
    title_en: "Writing and Publishing Project",
    description_ar: "رحلة 60 يومًا لبناء عادة كتابة منتظمة ونشر محتوى نافع بانتظام لجمهور حقيقي",
    description_en: "A 60-day journey building a regular writing habit and consistently publishing beneficial content for a real audience",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    durationDays: 60,
    dailyCommitmentMinutes: 35,
    milestones: [
      { day: 15, title_ar: "أول عشرة مقالات أو منشورات نُشرت", title_en: "The first ten articles or posts published", reward: { xp: 45, badge: "بداية النشر" } },
      { day: 30, title_ar: "نصف الرحلة مع صوت كتابي أوضح", title_en: "Halfway through, with a clearer writing voice", reward: { xp: 55, badge: "صوت متبلور" } },
      { day: 45, title_ar: "الكتابة والنشر أصبحا عادة لا مجهودًا استثنائيًا", title_en: "Writing and publishing have become habit, not exceptional effort", reward: { xp: 60, badge: "عادة راسخة" } },
      { day: 60, title_ar: "ستون يومًا من الكتابة والنشر المنتظمين", title_en: "Sixty days of regular writing and publishing", reward: { xp: 75, badge: "كاتب منتظم" } },
    ],
    finalReward: { xp: 210, badge: "🏅 صاحب عادة الكتابة والنشر", title_ar: "الكاتب" },
    icon: "✍️",
    successStories: [
      "من نشر بانتظام رغم الخوف الأولي من الحكم عليه، وجد صوتًا كتابيًا لم يكن يعرف أن لديه",
      "الاستمرارية في النشر بنت جمهورًا صغيرًا لكن حقيقيًا، لم يتوقعه في بداية الرحلة",
    ],
  },
  {
    id: "project_research_contribution",
    title_ar: "مشروع البحث والمساهمة المعرفية",
    title_en: "Research and Knowledge Contribution Project",
    description_ar: "رحلة 90 يومًا للتعمق في مجال بحثي وإنتاج مساهمة معرفية حقيقية فيه",
    description_en: "A 90-day journey diving deep into a research field and producing a genuine knowledge contribution within it",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    durationDays: 90,
    dailyCommitmentMinutes: 50,
    milestones: [
      { day: 25, title_ar: "مراجعة الأدبيات الأساسية للمجال اكتملت", title_en: "The field's foundational literature review completed", reward: { xp: 55, badge: "أساس بحثي" } },
      { day: 50, title_ar: "نصف الرحلة مع منهجية بحثية واضحة", title_en: "Halfway through, with a clear research methodology", reward: { xp: 70, badge: "منهجية راسخة" } },
      { day: 75, title_ar: "مسودة المساهمة المعرفية اكتملت", title_en: "The draft of the knowledge contribution completed", reward: { xp: 80, badge: "مسودة جاهزة" } },
      { day: 90, title_ar: "تسعون يومًا انتهت بمساهمة معرفية حقيقية", title_en: "Ninety days culminating in a genuine knowledge contribution", reward: { xp: 100, badge: "مساهم معرفي" } },
    ],
    finalReward: { xp: 270, badge: "🏅 صاحب المساهمة البحثية", title_ar: "الباحث" },
    icon: "🔬",
    successStories: [
      "من التزم بساعة بحث يومية دون استثناء، أنتج في ثلاثة أشهر ما كان يظنه يحتاج سنة كاملة",
      "المنهجية الواضحة منذ البداية وفّرت أسابيع كانت ستُهدر في التخبط دون خطة",
    ],
  },
];
