import type { HabitTemplate } from "../types";

/**
 * 40 health habits, 10 per difficulty tier, covering nutrition, movement,
 * sleep, hydration, mental health, hygiene, recovery, and medical checkups.
 *
 * Deliberate safety constraints applied throughout (advanced/expert tiers):
 * no specific calorie/macro numbers, no numbered intermittent-fasting
 * windows (e.g. 16:8), no cold-exposure temperatures, no detailed
 * longevity protocols. Anything touching fasting, extended eating
 * patterns, or intense physical protocols is phrased generally and
 * explicitly deferred to professional/medical supervision rather than
 * given as a followable spec.
 */
export const healthHabits: HabitTemplate[] = [
  // ===== Beginner (minLevel 1, xp 10-20) =====
  {
    id: "health_water_on_waking",
    title_ar: "شرب كوب ماء عند الاستيقاظ",
    title_en: "Drink a Glass of Water Upon Waking",
    description_ar: "شرب كوب ماء فور الاستيقاظ لترطيب الجسم بعد ساعات النوم",
    description_en: "Drink a glass of water right after waking to rehydrate after sleep",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 1, strength: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 2,
    icon: "💧",
    tags: ["ترطيب", "صباح", "يومي"],
    motivationalQuotes: [
      "أول كوب ماء يوقظ الجسم قبل أي شيء آخر",
      "عادة بسيطة، أثرها يمتد ليومك كاملاً",
      "الترطيب المبكر يمنحك نشاطًا حقيقيًا لا مؤقتًا",
    ],
  },
  {
    id: "health_ten_min_walk",
    title_ar: "المشي 10 دقائق يوميًا",
    title_en: "10-Minute Daily Walk",
    description_ar: "المشي لعشر دقائق متواصلة في أي وقت يناسبك خلال اليوم",
    description_en: "Walk for ten continuous minutes at any convenient time during the day",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { strength: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🚶",
    tags: ["مشي", "حركة", "يومي"],
    motivationalQuotes: [
      "عشر دقائق تكفي لتنشيط الجسم كله",
      "خطوة اليوم تصنع طريق الغد",
      "الحركة القليلة المنتظمة، خير من الكسل الطويل",
    ],
  },
  {
    id: "health_five_min_stretch",
    title_ar: "تمارين تمدد 5 دقائق",
    title_en: "5-Minute Stretching",
    description_ar: "جلسة تمدد قصيرة لإرخاء العضلات وتحسين المرونة",
    description_en: "A short stretching session to relax muscles and improve flexibility",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { strength: 1, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 5,
    icon: "🧘",
    tags: ["تمدد", "مرونة", "يومي"],
    motivationalQuotes: [
      "جسم مرن، حركة أسهل طوال اليوم",
      "خمس دقائق تمنع تصلب ساعات الجلوس",
      "التمدد البسيط استثمار في راحتك اللاحقة",
    ],
  },
  {
    id: "health_brush_teeth_twice",
    title_ar: "تنظيف الأسنان مرتين يوميًا",
    title_en: "Brush Teeth Twice Daily",
    description_ar: "المحافظة على تنظيف الأسنان صباحًا ومساءً بانتظام",
    description_en: "Maintain regular teeth brushing in the morning and evening",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 4,
    icon: "🦷",
    tags: ["نظافة", "أسنان", "يومي"],
    motivationalQuotes: [
      "عادة صغيرة تحمي صحتك لعقود قادمة",
      "الاهتمام بالتفاصيل اليومية أساس الصحة العامة",
      "دقيقتان مرتين يوميًا، ثمن بسيط لابتسامة صحية",
    ],
  },
  {
    id: "health_sleep_before_midnight",
    title_ar: "النوم قبل منتصف الليل",
    title_en: "Sleep Before Midnight",
    description_ar: "المحافظة على موعد نوم منتظم قبل الساعة الثانية عشرة ليلاً",
    description_en: "Maintain a regular bedtime before midnight",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 14,
    statsBoost: { discipline: 2, spirit: 1 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 5,
    icon: "🛌",
    tags: ["نوم", "انتظام", "يومي"],
    motivationalQuotes: [
      "نوم منتظم، يوم تالٍ أكثر وضوحًا",
      "الجسم يشفي نفسه في ساعات النوم المبكرة",
      "من نام مبكرًا، استيقظ بطاقة حقيقية",
    ],
  },
  {
    id: "health_veggie_with_meal",
    title_ar: "حصة خضار مع كل وجبة رئيسية",
    title_en: "A Serving of Vegetables with Each Main Meal",
    description_ar: "إضافة حصة واحدة على الأقل من الخضار لكل وجبة رئيسية",
    description_en: "Add at least one serving of vegetables to each main meal",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { wisdom: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🥦",
    tags: ["تغذية", "خضار", "يومي"],
    motivationalQuotes: [
      "طبق ملوّن، جسم أكثر توازنًا",
      "إضافة صغيرة لكل وجبة، أثرها يتراكم بمرور الوقت",
      "الاختيار الواعي في كل وجبة يبني عادة صحية دائمة",
    ],
  },
  {
    id: "health_three_deep_breaths",
    title_ar: "ثلاثة أنفاس عميقة عند التوتر",
    title_en: "Three Deep Breaths When Stressed",
    description_ar: "أخذ ثلاثة أنفاس عميقة وبطيئة عند الشعور بالتوتر أو الانفعال",
    description_en: "Take three slow, deep breaths whenever you feel stressed or overwhelmed",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { spirit: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 2,
    icon: "🌬️",
    tags: ["تنفس", "هدوء", "صحة نفسية"],
    motivationalQuotes: [
      "نفس عميق واحد، يعيد ضبط لحظتك",
      "الهدوء يبدأ من التنفس قبل أي شيء آخر",
      "لحظة توقف صغيرة تمنع ردة فعل كبيرة",
    ],
  },
  {
    id: "health_good_posture",
    title_ar: "الانتباه لوضعية الجلوس السليمة",
    title_en: "Mindful of Good Sitting Posture",
    description_ar: "تذكّر تصحيح وضعية الجلوس بانتظام خلال ساعات العمل",
    description_en: "Remember to correct your sitting posture regularly during work hours",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { strength: 1, discipline: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 1,
    icon: "🪑",
    tags: ["وضعية", "ظهر", "يومي"],
    motivationalQuotes: [
      "ظهر مستقيم، طاقة أعلى وألم أقل لاحقًا",
      "وعي بسيط بجسمك يمنع مشاكل مستقبلية",
      "الوضعية الجيدة عادة تُبنى بالتذكر المتكرر",
    ],
  },
  {
    id: "health_healthy_swap",
    title_ar: "استبدال صحي واحد يوميًا",
    title_en: "One Healthy Swap Daily",
    description_ar: "استبدال خيار غذائي واحد بديل أكثر فائدة كل يوم، دون تقييد صارم",
    description_en: "Replace one food choice with a more beneficial alternative each day, without strict restriction",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { wisdom: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🔄",
    tags: ["تغذية", "وعي", "يومي"],
    motivationalQuotes: [
      "استبدال واحد صغير، تراكمه كبير مع الوقت",
      "الوعي بالاختيار أهم من الحرمان الصارم",
      "تغيير تدريجي يدوم أكثر من تغيير مفاجئ",
    ],
  },
  {
    id: "health_hand_washing",
    title_ar: "غسل اليدين بانتظام",
    title_en: "Regular Hand Washing",
    description_ar: "المحافظة على غسل اليدين جيدًا قبل الأكل وبعد الأنشطة اليومية",
    description_en: "Maintain thorough hand washing before eating and after daily activities",
    category: "health",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 1,
    icon: "🧼",
    tags: ["نظافة", "وقاية", "يومي"],
    motivationalQuotes: [
      "عادة بسيطة، حماية حقيقية من العدوى",
      "النظافة أساس الوقاية، لا رفاهية إضافية",
      "ثوانٍ قليلة تحمي صحتك وصحة من حولك",
    ],
  },

  // ===== Intermediate (minLevel 15, xp 20-35) =====
  {
    id: "health_two_liters_water",
    title_ar: "شرب لترين ماء يوميًا",
    title_en: "Drinking Two Liters of Water Daily",
    description_ar: "المحافظة على شرب كمية كافية من الماء موزعة على اليوم",
    description_en: "Maintain adequate water intake spread throughout the day",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { discipline: 2, strength: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🚰",
    tags: ["ترطيب", "انتظام", "يومي"],
    motivationalQuotes: [
      "ترطيب منتظم، تركيز وطاقة أوضح طوال اليوم",
      "الماء وقود الجسم الصامت الذي يُنسى غالبًا",
      "عادة بسيطة تحدث فرقًا محسوسًا خلال أسابيع",
    ],
  },
  {
    id: "health_eight_thousand_steps",
    title_ar: "8000 خطوة يوميًا",
    title_en: "8,000 Steps Daily",
    description_ar: "الوصول لثمانية آلاف خطوة موزعة على اليوم من خلال الحركة الطبيعية",
    description_en: "Reach eight thousand steps spread across the day through natural movement",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { strength: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "👟",
    tags: ["مشي", "خطوات", "يومي"],
    motivationalQuotes: [
      "الحركة اليومية المنتظمة أساس صحة القلب",
      "ثماني آلاف خطوة، أقرب مما تتخيل حين توزعها",
      "جسم متحرك، مزاج أفضل ونوم أعمق",
    ],
  },
  {
    id: "health_weekly_exercise_30min",
    title_ar: "تمرين 30 دقيقة (3 أيام أسبوعيًا)",
    title_en: "30-Minute Exercise (3 Days a Week)",
    // Custom: يُترك للمستخدم اختيار الأيام المناسبة لجدوله الأسبوعي
    description_ar: "ممارسة نشاط بدني متوسط الشدة لثلاثين دقيقة، ثلاث مرات أسبوعيًا",
    description_en: "Engage in moderate-intensity physical activity for thirty minutes, three times a week",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 30,
    statsBoost: { strength: 4, discipline: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🏃",
    tags: ["رياضة", "تمرين", "أسبوعي"],
    motivationalQuotes: [
      "ثلاث جلسات أسبوعيًا كافية لبناء لياقة حقيقية",
      "الانتظام أهم من الشدة في بداية الطريق",
      "جسم نشيط، عقل أكثر صفاء",
    ],
  },
  {
    id: "health_seven_hours_sleep",
    title_ar: "المحافظة على 7 ساعات نوم",
    title_en: "Maintaining 7 Hours of Sleep",
    description_ar: "المحافظة على قدر كافٍ من النوم يوميًا لدعم التعافي والتركيز",
    description_en: "Maintain adequate daily sleep to support recovery and focus",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { discipline: 3, spirit: 2 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 5,
    icon: "😴",
    tags: ["نوم", "تعافي", "يومي"],
    motivationalQuotes: [
      "النوم الكافي استثمار، لا وقت ضائع",
      "الجسم يُصلح نفسه أثناء نومك، فامنحه الوقت الكافي",
      "قرار النوم مبكرًا، قرار يخدم يومك التالي بأكمله",
    ],
  },
  {
    id: "health_weekly_meal_prep",
    title_ar: "تحضير وجبات صحية أسبوعيًا",
    title_en: "Weekly Healthy Meal Preparation",
    // Custom: يُترك للمستخدم تحديد يوم التحضير المناسب لجدوله
    description_ar: "تخصيص وقت أسبوعي لتحضير وجبات متوازنة تسهّل خيارات صحية خلال الأسبوع",
    description_en: "Dedicate weekly time to preparing balanced meals that support healthy choices during the week",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { wisdom: 3, discipline: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🥗",
    tags: ["تغذية", "تحضير", "أسبوعي"],
    motivationalQuotes: [
      "التحضير المسبق يجعل الخيار الصحي هو الأسهل",
      "ساعة تحضير أسبوعيًا، توفر قرارات يومية أفضل",
      "من خطط لطعامه، لم يترك الأمر للصدفة أو الجوع",
    ],
  },
  {
    id: "health_ten_min_relaxation",
    title_ar: "جلسة استرخاء أو تأمل 10 دقائق",
    title_en: "10-Minute Relaxation or Meditation Session",
    description_ar: "جلسة يومية قصيرة للاسترخاء الذهني بعيدًا عن مصادر التوتر",
    description_en: "A short daily session for mental relaxation away from sources of stress",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { spirit: 4 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "🌿",
    tags: ["استرخاء", "صحة نفسية", "يومي"],
    motivationalQuotes: [
      "عشر دقائق سكون، توازن يمتد لبقية اليوم",
      "العقل يحتاج راحة كما يحتاج الجسم تمامًا",
      "الاسترخاء المنتظم يقوي مقاومتك للضغط اليومي",
    ],
  },
  {
    id: "health_reduce_screen_before_bed",
    title_ar: "تقليل الشاشات قبل النوم",
    title_en: "Reducing Screen Time Before Bed",
    description_ar: "الابتعاد عن شاشات الهاتف والحاسوب في الفترة التي تسبق النوم مباشرة",
    description_en: "Avoiding phone and computer screens in the period immediately before sleep",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { discipline: 3, spirit: 1 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 30,
    icon: "📴",
    tags: ["نوم", "شاشات", "يومي"],
    motivationalQuotes: [
      "ذهن هادئ قبل النوم، نوم أعمق وأسرع",
      "الشاشة المطفأة مبكرًا، نافذة نوم أفضل",
      "من حرر ليله من الشاشات، استعاد جودة نومه",
    ],
  },
  {
    id: "health_breathing_for_mental_health",
    title_ar: "تمارين تنفس للصحة النفسية",
    title_en: "Breathing Exercises for Mental Health",
    description_ar: "جلسة يومية قصيرة من تمارين التنفس المنظم لتهدئة الجهاز العصبي",
    description_en: "A short daily session of structured breathing exercises to calm the nervous system",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { spirit: 3, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 8,
    icon: "🫁",
    tags: ["تنفس", "صحة نفسية", "يومي"],
    motivationalQuotes: [
      "التنفس المنظم أداة متاحة دائمًا لضبط حالتك",
      "دقائق قليلة من التنفس الواعي، تهدئة حقيقية",
      "الجهاز العصبي يتعلم الهدوء بالممارسة المتكررة",
    ],
  },
  {
    id: "health_weekly_mood_journal",
    title_ar: "متابعة أسبوعية للطاقة والمزاج",
    title_en: "Weekly Energy and Mood Tracking",
    // Custom: يُترك للمستخدم تحديد يوم أسبوعي ثابت للمتابعة
    description_ar: "تدوين أسبوعي بسيط لملاحظة أنماط الطاقة والمزاج ومسبباتها",
    description_en: "A simple weekly log to notice patterns in energy and mood and their triggers",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { wisdom: 3, spirit: 1 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 15,
    icon: "📔",
    tags: ["صحة نفسية", "تأمل", "أسبوعي"],
    motivationalQuotes: [
      "الوعي بأنماطك النفسية خطوة أولى نحو تحسينها",
      "ما يُلاحَظ بانتظام، يمكن فهمه وتطويره",
      "متابعة بسيطة أسبوعيًا، فهم أعمق لنفسك",
    ],
  },
  {
    id: "health_balanced_breakfast",
    title_ar: "المحافظة على إفطار متوازن",
    title_en: "Maintaining a Balanced Breakfast",
    description_ar: "بدء اليوم بوجبة إفطار متوازنة تمنحك طاقة مستقرة للصباح",
    description_en: "Start the day with a balanced breakfast that provides steady morning energy",
    category: "health",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 20,
    statsBoost: { discipline: 2, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 15,
    icon: "🍳",
    tags: ["تغذية", "إفطار", "يومي"],
    motivationalQuotes: [
      "إفطار متوازن، صباح أكثر استقرارًا",
      "الوجبة الأولى تحدد نمط طاقتك لبقية اليوم",
      "بداية اليوم بوعي غذائي، عادة تُبنى بالتكرار",
    ],
  },

  // ===== Advanced (minLevel 35, xp 35-50) =====
  {
    id: "health_ten_thousand_steps",
    title_ar: "10,000 خطوة يوميًا",
    title_en: "10,000 Steps Daily",
    description_ar: "الوصول لعشرة آلاف خطوة يوميًا كمعيار نشاط بدني متقدم",
    description_en: "Reach ten thousand steps daily as an advanced physical activity benchmark",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { strength: 5, discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 75,
    icon: "🏃‍♂️",
    tags: ["مشي", "لياقة", "متقدم"],
    motivationalQuotes: [
      "عشرة آلاف خطوة، عادة تحمي قلبك على المدى الطويل",
      "الاستمرارية في الحركة تفوق أي جهد مؤقت",
      "من جعل الحركة نمط حياة، لم يعد يحتاج تحفيزًا خارجيًا",
    ],
  },
  {
    id: "health_resistance_training_4days",
    title_ar: "تمارين مقاومة أربعة أيام أسبوعيًا",
    title_en: "Resistance Training Four Days a Week",
    // Custom: يُترك للمستخدم تحديد الأيام المناسبة وبرنامج التمرين بإشراف مختص عند الحاجة
    description_ar: "ممارسة تمارين مقاومة منتظمة لبناء القوة، يُفضّل بإشراف مدرّب مختص",
    description_en: "Regular resistance training to build strength, ideally guided by a qualified trainer",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 45,
    statsBoost: { strength: 6, discipline: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🏋️",
    tags: ["قوة", "تمرين", "أسبوعي"],
    motivationalQuotes: [
      "القوة الجسدية تُبنى بالتكرار المنضبط لا بالاندفاع",
      "من استثمر في قوته، حصد استقلالية جسدية أطول",
      "التمرين المنتظم بإشراف صحيح، أساس تقدم آمن",
    ],
  },
  {
    id: "health_mindful_eating_pattern",
    title_ar: "نمط أكل منتظم وواعٍ",
    title_en: "A Regular, Mindful Eating Pattern",
    description_ar: "المحافظة على مواعيد أكل منتظمة وواعية دون اتباع قيود صارمة أو تفصيلية",
    description_en: "Maintain regular, mindful eating times without following strict or detailed restrictions",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { wisdom: 4, discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🍽️",
    tags: ["تغذية", "وعي", "متقدم"],
    motivationalQuotes: [
      "الوعي في الأكل أهم من القيود الصارمة",
      "انتظام المواعيد يخدم الجسم أكثر من التقييد المفاجئ",
      "الاستماع لإشارات جسمك، حكمة تفوق أي نظام جاهز",
    ],
  },
  {
    id: "health_brief_cold_shower",
    title_ar: "دش بارد قصير",
    title_en: "A Brief Cold Shower",
    description_ar: "إنهاء الاستحمام بلحظات من الماء البارد، بشكل تدريجي ومريح للجسم",
    description_en: "End your shower with a brief period of cold water, gradually and comfortably",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { discipline: 4, strength: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 3,
    icon: "🚿",
    tags: ["انتعاش", "انضباط", "يومي"],
    motivationalQuotes: [
      "لحظات قصيرة من التحدي، تبني انضباطًا يتجاوزها",
      "من تدرّب على الراحة خارج منطقته المعتادة، قوي إرادته",
      "بداية يوم منعشة، تنعكس على بقية ساعاته",
    ],
  },
  {
    id: "health_general_nutrition_awareness",
    title_ar: "متابعة عامة لتوازن العناصر الغذائية",
    title_en: "General Awareness of Nutritional Balance",
    description_ar: "ملاحظة عامة لتنوع وتوازن الوجبات دون تتبع أرقام دقيقة أو قيود صارمة",
    description_en: "General observation of meal variety and balance without tracking precise numbers or strict limits",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 35,
    statsBoost: { wisdom: 4 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "📊",
    tags: ["تغذية", "توازن", "وعي"],
    motivationalQuotes: [
      "التوازن العام أهم من الدقة المفرطة في الأرقام",
      "وعي مستمر بتنوع طعامك، خير من قيود مؤقتة",
      "من فهم احتياجات جسمه عمومًا، اتخذ قرارات أفضل باستمرار",
    ],
  },
  {
    id: "health_weekly_deep_stretch",
    title_ar: "جلسة تمدد عميقة أسبوعية",
    title_en: "Weekly Deep Stretching Session",
    // Custom: يُترك للمستخدم تحديد اليوم المناسب لجلسة التمدد الأطول
    description_ar: "جلسة أسبوعية أطول من تمارين التمدد لتحسين المرونة العامة للجسم",
    description_en: "A longer weekly stretching session to improve overall body flexibility",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { strength: 3, spirit: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 30,
    icon: "🤸",
    tags: ["مرونة", "تعافي", "أسبوعي"],
    motivationalQuotes: [
      "المرونة الجسدية تحمي من إصابات المستقبل",
      "جلسة تمدد عميقة، هدية أسبوعية لجسمك",
      "العناية بالمرونة، جزء مهمل غالبًا من اللياقة الحقيقية",
    ],
  },
  {
    id: "health_routine_medical_checkup",
    title_ar: "فحص طبي دوري روتيني",
    title_en: "Routine Medical Checkup",
    // Custom: يُترك للمستخدم تحديد الوتيرة المناسبة بالتنسيق مع طبيبه
    description_ar: "المحافظة على مواعيد فحوصات طبية دورية عامة بالتنسيق مع طبيبك",
    description_en: "Maintain regular general medical checkup appointments in coordination with your doctor",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { wisdom: 5 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🩺",
    tags: ["فحص طبي", "وقاية", "دوري"],
    motivationalQuotes: [
      "الفحص الدوري يكتشف ما لا تشعر به بعد",
      "الوقاية المنتظمة أرخص وأهدأ من العلاج المتأخر",
      "متابعة صحتك بجدية، احترام حقيقي لجسمك",
    ],
  },
  {
    id: "health_sleep_environment",
    title_ar: "تحسين بيئة النوم",
    title_en: "Improving Your Sleep Environment",
    description_ar: "ضبط الإضاءة والهدوء ودرجة حرارة الغرفة لدعم نوم أعمق",
    description_en: "Adjust lighting, quiet, and room temperature to support deeper sleep",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { wisdom: 3, spirit: 2 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 10,
    icon: "🌙",
    tags: ["نوم", "بيئة", "يومي"],
    motivationalQuotes: [
      "بيئة نوم مهيأة، جودة نوم مختلفة تمامًا",
      "تفاصيل صغيرة في غرفتك، فرق كبير في راحتك",
      "من أعدّ مكانه للنوم، احترم حاجة جسمه للتعافي",
    ],
  },
  {
    id: "health_weekly_relaxing_hobby",
    title_ar: "ممارسة هواية مريحة أسبوعيًا",
    title_en: "Weekly Relaxing Hobby Time",
    // Custom: يُترك للمستخدم اختيار الهواية والوقت المناسب أسبوعيًا
    description_ar: "تخصيص وقت أسبوعي لهواية تمنحك راحة نفسية بعيدًا عن ضغوط الحياة اليومية",
    description_en: "Dedicate weekly time to a hobby that brings mental relief away from daily pressures",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 35,
    statsBoost: { spirit: 4, creativity: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🎨",
    tags: ["هواية", "صحة نفسية", "أسبوعي"],
    motivationalQuotes: [
      "الراحة النفسية ليست ترفًا، بل جزء من الصحة",
      "هواية بسيطة، متنفس حقيقي وسط الانشغال",
      "من خصص وقتًا لمتعته، جدد طاقته لبقية أسبوعه",
    ],
  },
  {
    id: "health_weekly_social_support",
    title_ar: "تواصل أسبوعي مع صديق مقرب",
    title_en: "Weekly Connection with a Close Friend",
    // Custom: يُترك للمستخدم اختيار الشخص والوقت المناسب أسبوعيًا
    description_ar: "تخصيص وقت أسبوعي للتواصل الصادق مع صديق مقرب لدعم الصحة النفسية",
    description_en: "Dedicate weekly time for genuine connection with a close friend to support mental health",
    category: "health",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { spirit: 3, compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "👫",
    tags: ["دعم اجتماعي", "صحة نفسية", "أسبوعي"],
    motivationalQuotes: [
      "العلاقات الصادقة دعامة أساسية للصحة النفسية",
      "من له من يُشاركه، يحمل أعباءه بخفة أكبر",
      "التواصل المنتظم يحمي من العزلة الصامتة",
    ],
  },

  // ===== Expert (minLevel 60, xp 50-80) =====
  {
    id: "health_supervised_training_program",
    title_ar: "برنامج تدريبي احترافي بإشراف مختص",
    title_en: "Professional Training Program Under Expert Supervision",
    // Custom: يُترك للمستخدم وضع البرنامج بالتنسيق الكامل مع مدرّب مختص
    description_ar: "اتباع برنامج تدريبي متقدم مصمم ومتابَع من قبل مدرّب أو مختص لياقة مؤهل",
    description_en: "Follow an advanced training program designed and monitored by a qualified coach or fitness expert",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 65,
    statsBoost: { strength: 7, discipline: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 75,
    icon: "🏆",
    tags: ["تدريب متقدم", "إشراف مختص", "خبير"],
    motivationalQuotes: [
      "التقدم الحقيقي في اللياقة يحتاج توجيهًا مختصًا لا اجتهادًا فرديًا",
      "من استثمر في إشراف مؤهل، حمى نفسه وسرّع تقدمه معًا",
      "الانضباط طويل الأمد يحتاج خطة مدروسة لا حماسًا وحده",
    ],
  },
  {
    id: "health_annual_endurance_goal",
    title_ar: "الاستعداد لهدف تحمّل سنوي",
    title_en: "Preparing for an Annual Endurance Goal",
    // Custom: يُترك للمستخدم تحديد الهدف والجدول بالتنسيق مع مختص لياقة
    description_ar: "العمل التدريجي والمنظم نحو هدف تحمّل بدني سنوي، بإشراف مختص لضمان السلامة",
    description_en: "Gradual, structured progress toward an annual endurance goal, supervised by an expert for safety",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 70,
    statsBoost: { strength: 6, discipline: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🏅",
    tags: ["تحمّل", "هدف سنوي", "إشراف مختص"],
    motivationalQuotes: [
      "الأهداف الكبرى تُبنى بخطوات صغيرة مدروسة",
      "من صبر على التدرج الآمن، وصل بلا إصابات توقفه",
      "التحضير المنظم يحوّل الحلم الكبير إلى خطة قابلة للتحقيق",
    ],
  },
  {
    id: "health_extended_eating_pattern_supervised",
    title_ar: "نمط أكل ممتد بإشراف متخصص",
    title_en: "Extended Eating Pattern Under Professional Supervision",
    // Custom: أي نمط أكل ممتد يجب أن يكون بإشراف مختص تغذية أو طبيب مباشر، دون اتباع تفاصيل جاهزة من التطبيق
    description_ar: "أي نمط أكل ممتد يجب أن يكون بإشراف مختص تغذية أو طبيب مباشر، دون اتباع تفاصيل جاهزة",
    description_en: "Any extended eating pattern should be undertaken only under the direct supervision of a nutrition specialist or physician, not by following unsupervised prescriptions",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 55,
    statsBoost: { discipline: 5, wisdom: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🩺",
    tags: ["تغذية متقدمة", "إشراف طبي", "أمان"],
    motivationalQuotes: [
      "السلامة أولًا، حتى في أكثر الممارسات تقدمًا",
      "الإشراف المختص يحوّل التجربة الخطرة إلى خطوة آمنة",
      "من استشار قبل أن يُقدم، حمى نفسه من قرارات متسرعة",
    ],
  },
  {
    id: "health_supportive_long_term_lifestyle",
    title_ar: "نمط حياة داعم للصحة على المدى الطويل",
    title_en: "A Lifestyle Supporting Long-Term Health",
    description_ar: "المحافظة العامة على توازن التغذية والحركة والنوم والراحة النفسية كأسلوب حياة مستدام",
    description_en: "General maintenance of balanced nutrition, movement, sleep, and mental rest as a sustainable lifestyle",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { wisdom: 6, spirit: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🌳",
    tags: ["نمط حياة", "استدامة", "توازن"],
    motivationalQuotes: [
      "الصحة المستدامة تُبنى بتوازن يومي، لا بإنجازات مؤقتة",
      "من عاش بتوازن، حصد صحة تدوم لا تلمع فقط",
      "الاستمرارية الهادئة تتفوق على الحماس المؤقت دائمًا",
    ],
  },
  {
    id: "health_advanced_medical_screening",
    title_ar: "الفحوصات الطبية المتقدمة الدورية",
    title_en: "Regular Advanced Medical Screening",
    // Custom: يُترك للمستخدم تحديد الوتيرة والفحوصات المناسبة بالكامل بتوجيه طبيبه
    description_ar: "المحافظة على فحوصات طبية متقدمة دورية يحددها الطبيب المختص حسب الحالة الفردية",
    description_en: "Maintain regular advanced medical screenings as determined by a physician based on individual needs",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { wisdom: 5 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🔬",
    tags: ["فحوصات متقدمة", "وقاية", "إشراف طبي"],
    motivationalQuotes: [
      "المتابعة الطبية المتقدمة استثمار طويل الأمد في نوعية حياتك",
      "من تابع صحته بجدية، اكتشف المشكلات قبل تفاقمها",
      "القرارات الصحية الكبرى، أفضل ما تُتخذ بمعرفة دقيقة",
    ],
  },
  {
    id: "health_guide_others_wellness",
    title_ar: "توجيه آخرين في رحلتهم الصحية",
    title_en: "Guiding Others in Their Health Journey",
    // Custom: يُترك للمستخدم تحديد الأشخاص والوتيرة المناسبة
    description_ar: "دعم شخص آخر بمشاركة تجربتك وتشجيعه على بناء عادات صحية بأسلوب آمن ومسؤول",
    description_en: "Support someone else by sharing your experience and encouraging safe, responsible healthy habits",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 56,
    statsBoost: { compassion: 5, influence: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🤲",
    tags: ["دعم", "توجيه", "أثر"],
    motivationalQuotes: [
      "من ساعد غيره على البدء، ضاعف أثر رحلته الخاصة",
      "التشجيع الصادق قد يكون بداية تحوّل حقيقي لشخص آخر",
      "مشاركة تجربتك بمسؤولية، هدية لا تُقدَّر بثمن",
    ],
  },
  {
    id: "health_planned_recovery_cycles",
    title_ar: "التوازن بين التدريب ودورات التعافي المخططة",
    title_en: "Balancing Training with Planned Recovery Cycles",
    description_ar: "دمج فترات راحة مخططة ضمن برنامج التدريب لمنع الإرهاق والإصابات",
    description_en: "Integrate planned rest periods into your training program to prevent burnout and injury",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 54,
    statsBoost: { wisdom: 4, strength: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "♻️",
    tags: ["تعافي", "توازن", "لياقة"],
    motivationalQuotes: [
      "التعافي جزء من التدريب، لا توقف عنه",
      "الجسم يتقدم في الراحة كما يتقدم في الجهد",
      "من تجاهل التعافي، دفع ثمنه إصابة أو إرهاقًا لاحقًا",
    ],
  },
  {
    id: "health_family_wellness_leadership",
    title_ar: "القيادة الصحية داخل الأسرة",
    title_en: "Leading Wellness Within the Family",
    // Custom: يُترك للمستخدم تحديد الأنشطة والوتيرة المناسبة لأسرته
    description_ar: "قيادة عادات صحية بسيطة ومشتركة داخل الأسرة بروح إيجابية غير مفروضة",
    description_en: "Lead simple, shared healthy habits within the family in a positive, non-imposing spirit",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 52,
    statsBoost: { influence: 4, compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "👨‍👩‍👧‍👦",
    tags: ["أسرة", "قيادة صحية", "أثر"],
    motivationalQuotes: [
      "القدوة العملية أقوى من كل نصيحة مباشرة",
      "أسرة صحية تبدأ بفرد واحد يقود بلطف لا بإلزام",
      "عاداتك أمام أطفالك، درس يتعلمونه دون أن تقوله",
    ],
  },
  {
    id: "health_advanced_stress_management",
    title_ar: "إتقان تقنيات إدارة التوتر المتقدمة",
    title_en: "Mastering Advanced Stress Management Techniques",
    // Custom: عند الحاجة لدعم إضافي، يُنصح بالتواصل مع مختص صحة نفسية مؤهل
    description_ar: "تطوير مجموعة أدوات شخصية متقدمة للتعامل مع التوتر، مع التوجه لمختص عند الحاجة",
    description_en: "Develop an advanced personal toolkit for managing stress, seeking a qualified specialist when needed",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { spirit: 6, wisdom: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "🧠",
    tags: ["إدارة التوتر", "صحة نفسية", "خبير"],
    motivationalQuotes: [
      "إتقان التعامل مع التوتر مهارة تُصقل، لا تأتي بالصدفة",
      "طلب الدعم المتخصص عند الحاجة، قوة لا ضعف",
      "من بنى أدوات نفسية متينة، واجه الصعاب بثبات أكبر",
    ],
  },
  {
    id: "health_preventive_investment",
    title_ar: "الاستثمار طويل الأمد في الصحة الوقائية",
    title_en: "Long-Term Investment in Preventive Health",
    // Custom: يُترك للمستخدم تحديد الجدول بالتنسيق مع فريقه الطبي
    description_ar: "المحافظة على استشارات وفحوصات وقائية منتظمة كجزء من رؤية صحية طويلة المدى",
    description_en: "Maintain regular preventive consultations and screenings as part of a long-term health vision",
    category: "health",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { wisdom: 6 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🛡️",
    tags: ["وقاية", "استثمار طويل الأمد", "خبير"],
    motivationalQuotes: [
      "الوقاية استثمار لا يُرى أثره فورًا، لكنه الأكبر على المدى البعيد",
      "من رعى صحته اليوم، وسّع خياراته في الغد",
      "الرؤية الصحية طويلة الأمد، أثمن هدية تمنحها لنفسك",
    ],
  },
];
