import type { HabitTemplate } from "../types";

/**
 * 40 learning habits, 10 per difficulty tier, covering reading, writing,
 * digital learning, language acquisition, memory techniques, critical
 * thinking, creativity, teaching, research, and practical skills.
 *
 * About a third of the habits carry a general Islamic wisdom reference on
 * seeking and sharing knowledge, phrased by meaning rather than as a
 * verbatim hadith quotation, to avoid misattribution risk while keeping
 * the cultural resonance established in spiritual.ts.
 */
export const learningHabits: HabitTemplate[] = [
  // ===== Beginner (minLevel 1, xp 10-20) =====
  {
    id: "learning_ten_pages_daily",
    title_ar: "قراءة 10 صفحات يوميًا",
    title_en: "Read 10 Pages Daily",
    description_ar: "تخصيص وقت يومي لقراءة عشر صفحات على الأقل من كتاب مفيد",
    description_en: "Dedicate daily time to reading at least ten pages of a useful book",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 14,
    statsBoost: { intelligence: 2, discipline: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 20,
    icon: "📖",
    tags: ["قراءة", "كتب", "يومي"],
    motivationalQuotes: [
      "طلب العلم رحلة تبدأ بصفحة واحدة",
      "عشر صفحات يوميًا، تصنع مكتبة كاملة خلال عام",
      "القراءة المنتظمة تبني عقلاً لا يتوقف عن النمو",
    ],
  },
  {
    id: "learning_new_english_word",
    title_ar: "تعلم كلمة إنجليزية جديدة",
    title_en: "Learn a New English Word",
    description_ar: "إضافة كلمة إنجليزية جديدة لمفرداتك يوميًا مع مثال على استخدامها",
    description_en: "Add a new English word to your vocabulary daily with a usage example",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { intelligence: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🔤",
    tags: ["لغة", "مفردات", "يومي"],
    motivationalQuotes: [
      "كلمة جديدة يوميًا، ثلاثمئة وستون كلمة كل عام",
      "طلب العلم فريضة على كل مسلم، ولو كان حرفًا واحدًا في كل مرة",
      "من راكم قليلاً كل يوم، امتلك كثيرًا بمرور الوقت",
    ],
  },
  {
    id: "learning_educational_podcast",
    title_ar: "بودكاست تعليمي 15 دقيقة",
    title_en: "15-Minute Educational Podcast",
    description_ar: "الاستماع لحلقة بودكاست تعليمية قصيرة تضيف معرفة جديدة",
    description_en: "Listen to a short educational podcast episode that adds new knowledge",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { intelligence: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🎧",
    tags: ["بودكاست", "استماع", "يومي"],
    motivationalQuotes: [
      "خمس عشرة دقيقة من الاستماع الواعي، معرفة تتراكم",
      "التعلم لا يحتاج مكتبًا، يكفي وقت وأذن مصغية",
      "من استغل وقته المتنقل بالتعلم، ضاعف يومه",
    ],
  },
  {
    id: "learning_daily_journaling",
    title_ar: "كتابة يومية (Journaling)",
    title_en: "Daily Journaling",
    description_ar: "تدوين أفكارك ومشاعرك وملاحظاتك في يوميات شخصية كل يوم",
    description_en: "Write down your thoughts, feelings, and observations in a personal journal daily",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { creativity: 2, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "📓",
    tags: ["كتابة", "تأمل", "يومي"],
    motivationalQuotes: [
      "الكتابة توضح الأفكار التي تبقى مشوشة في الذهن",
      "يوميات صادقة، مرآة صافية لنموك الشخصي",
      "من كتب عن يومه، فهمه بشكل أعمق",
    ],
  },
  {
    id: "learning_daily_curious_question",
    title_ar: "طرح سؤال فضولي يوميًا",
    title_en: "Ask One Curious Question Daily",
    description_ar: "طرح سؤال واحد يثير فضولك عن العالم من حولك، والبحث عن إجابته لاحقًا",
    description_en: "Ask one question that sparks your curiosity about the world, and seek its answer later",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { intelligence: 2, creativity: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "❓",
    tags: ["فضول", "أسئلة", "يومي"],
    motivationalQuotes: [
      "من سلك طريقًا يلتمس فيه علمًا، سلك الله به طريقًا إلى الخير",
      "السؤال الفضولي بداية كل اكتشاف",
      "العقل الذي يسأل باستمرار، لا يتوقف عن التعلم",
    ],
  },
  {
    id: "learning_review_notes",
    title_ar: "مراجعة الملاحظات اليومية",
    title_en: "Reviewing Daily Notes",
    description_ar: "تخصيص وقت قصير لمراجعة ما دوّنته من ملاحظات خلال اليوم",
    description_en: "Dedicate short time to reviewing the notes you took during the day",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { intelligence: 1, discipline: 1 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "🗒️",
    tags: ["مراجعة", "ملاحظات", "يومي"],
    motivationalQuotes: [
      "ما لا يُراجَع، يُنسى مهما كان مهمًا",
      "العلم صيد والكتابة قيده، فلا يُترك بلا مراجعة",
      "دقائق قليلة من المراجعة، توفر ساعات من إعادة التعلم",
    ],
  },
  {
    id: "learning_short_educational_video",
    title_ar: "مشاهدة فيديو تعليمي قصير",
    title_en: "Watching a Short Educational Video",
    description_ar: "مشاهدة فيديو تعليمي قصير يضيف معلومة أو مهارة جديدة",
    description_en: "Watch a short educational video that adds a new piece of knowledge or skill",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { intelligence: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🎬",
    tags: ["فيديو", "تعلم رقمي", "يومي"],
    motivationalQuotes: [
      "دقائق معدودة قد تفتح لك بابًا معرفيًا جديدًا",
      "التعلم المرئي يبسط المفاهيم الصعبة",
      "من استغل الوسائط المتاحة، تعلم دون عناء كبير",
    ],
  },
  {
    id: "learning_memorize_one_fact",
    title_ar: "حفظ معلومة جديدة يوميًا",
    title_en: "Memorizing One New Fact Daily",
    description_ar: "حفظ معلومة أو حقيقة جديدة كل يوم وربطها بما تعرفه سابقًا",
    description_en: "Memorize one new fact daily and connect it to what you already know",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { intelligence: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🧠",
    tags: ["حفظ", "معلومات", "يومي"],
    motivationalQuotes: [
      "معلومة واحدة يوميًا، معرفة واسعة خلال عام",
      "الربط بين المعلومات الجديدة والقديمة يثبّت الحفظ",
      "عقل يتغذى يوميًا بمعرفة جديدة، لا يشيخ بسرعة",
    ],
  },
  {
    id: "learning_reading_before_sleep",
    title_ar: "القراءة قبل النوم",
    title_en: "Reading Before Sleep",
    description_ar: "قراءة صفحات قليلة قبل النوم بدلاً من استخدام الشاشات",
    description_en: "Read a few pages before sleeping instead of using screens",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { intelligence: 1, spirit: 1 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 15,
    icon: "🌙",
    tags: ["قراءة", "نوم", "يومي"],
    motivationalQuotes: [
      "لا يزال العالِم عالِمًا ما دام يتعلم، فإذا ظن أنه استغنى جهل",
      "آخر نشاط في يومك، اجعله نافعًا لعقلك",
      "قراءة هادئة قبل النوم، بديل صحي عن الشاشات",
    ],
  },
  {
    id: "learning_creative_idea_log",
    title_ar: "تدوين فكرة إبداعية يوميًا",
    title_en: "Logging One Creative Idea Daily",
    description_ar: "تدوين فكرة إبداعية واحدة تخطر ببالك كل يوم، مهما بدت بسيطة",
    description_en: "Write down one creative idea that crosses your mind daily, however simple it seems",
    category: "learning",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { creativity: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "💡",
    tags: ["إبداع", "أفكار", "يومي"],
    motivationalQuotes: [
      "الأفكار العظيمة تبدأ صغيرة ومدوَّنة",
      "فكرة غير مكتوبة، فكرة معرّضة للنسيان",
      "عادة التدوين تحول الخواطر العابرة إلى مشاريع حقيقية",
    ],
  },

  // ===== Intermediate (minLevel 15, xp 20-35) =====
  {
    id: "learning_one_book_monthly",
    title_ar: "إنهاء كتاب كامل شهريًا",
    title_en: "Finishing One Full Book Monthly",
    // Custom: يُترك للمستخدم اختيار الكتاب المناسب كل شهر
    description_ar: "المحافظة على وتيرة قراءة تكفي لإنهاء كتاب كامل كل شهر",
    description_en: "Maintain a reading pace sufficient to finish one complete book each month",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 30,
    statsBoost: { intelligence: 4, discipline: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "📚",
    tags: ["قراءة", "كتب", "شهري"],
    motivationalQuotes: [
      "اثنا عشر كتابًا كل عام، مكتبة معرفية متنامية",
      "الوتيرة المنتظمة أهم من سرعة القراءة",
      "من التزم بكتاب شهريًا، بنى عادة تدوم مدى الحياة",
    ],
  },
  {
    id: "learning_quarterly_course",
    title_ar: "دورة تدريبية كل ثلاثة أشهر",
    title_en: "A Training Course Every Quarter",
    // Custom: يُترك للمستخدم اختيار الدورة المناسبة لاهتماماته كل ثلاثة أشهر
    description_ar: "التسجيل وإكمال دورة تدريبية جديدة كل ثلاثة أشهر لتطوير مهارة محددة",
    description_en: "Enroll in and complete a new training course every three months to develop a specific skill",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 32,
    statsBoost: { intelligence: 3, discipline: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 45,
    icon: "🎓",
    tags: ["دورات", "تعلم رقمي", "دوري"],
    motivationalQuotes: [
      "دورة كل ربع سنة، أربع مهارات جديدة كل عام",
      "الاستثمار في التعلم المنظم يفوق التعلم العشوائي",
      "من خطط لتعلمه، حقق تقدمًا ملموسًا كل فصل",
    ],
  },
  {
    id: "learning_daily_language_practice",
    title_ar: "تطبيق لغة يوميًا",
    title_en: "Daily Language Practice",
    description_ar: "ممارسة يومية للغة تتعلمها عبر المحادثة أو التمارين أو الاستماع",
    description_en: "Daily practice of a language you're learning through conversation, exercises, or listening",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { intelligence: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "🗣️",
    tags: ["لغة", "ممارسة", "يومي"],
    motivationalQuotes: [
      "اللغة تُتقَن بالممارسة، لا بالحفظ وحده",
      "عشرون دقيقة يوميًا، طلاقة تتراكم بصمت",
      "من مارس لغته يوميًا، لم ينسَ ما تعلمه",
    ],
  },
  {
    id: "learning_organized_note_system",
    title_ar: "تدوين ملاحظات منظم",
    title_en: "Organized Note-Taking System",
    description_ar: "المحافظة على نظام واضح لتدوين وتصنيف ما تتعلمه لسهولة الرجوع إليه",
    description_en: "Maintain a clear system for taking and categorizing notes on what you learn for easy retrieval",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { wisdom: 3, discipline: 2 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 15,
    icon: "🗂️",
    tags: ["ملاحظات", "تنظيم", "يومي"],
    motivationalQuotes: [
      "نظام واضح للملاحظات، معرفة سهلة الاسترجاع",
      "من قيّد علمه بالتنظيم، حفظه ولم يفلته النسيان",
      "من صنّف ما تعلمه، استفاد منه حين يحتاجه",
    ],
  },
  {
    id: "learning_weekly_critical_thinking",
    title_ar: "جلسة تفكير نقدي أسبوعية",
    title_en: "Weekly Critical Thinking Session",
    // Custom: يُترك للمستخدم اختيار الموضوع المناسب للتحليل كل أسبوع
    description_ar: "تخصيص جلسة أسبوعية لتحليل موضوع أو قرار بعمق من زوايا متعددة",
    description_en: "Dedicate a weekly session to deeply analyzing a topic or decision from multiple angles",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { wisdom: 4, intelligence: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 30,
    icon: "🔍",
    tags: ["تفكير نقدي", "تحليل", "أسبوعي"],
    motivationalQuotes: [
      "التفكير النقدي يميّز الفهم العميق عن السطحي",
      "العقل الذي يتدبر، أقرب إلى الفهم الذي يدعو إليه طلب العلم",
      "جلسة تفكير أسبوعية، عقل أكثر وعيًا بمرور الوقت",
    ],
  },
  {
    id: "learning_summarize_reading",
    title_ar: "تلخيص ما تقرأه",
    title_en: "Summarizing What You Read",
    description_ar: "كتابة ملخص قصير لأهم الأفكار بعد كل جلسة قراءة أو تعلم",
    description_en: "Write a short summary of key ideas after each reading or learning session",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { intelligence: 3, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "📝",
    tags: ["تلخيص", "فهم", "يومي"],
    motivationalQuotes: [
      "من استطاع أن يلخّص، فهم حقًا ما قرأه",
      "التلخيص يحوّل القراءة السلبية إلى تعلم فعّال",
      "أفكار موجزة ومكتوبة، أسهل للمراجعة لاحقًا",
    ],
  },
  {
    id: "learning_weekly_practical_skill",
    title_ar: "تعلم مهارة عملية جديدة أسبوعيًا",
    title_en: "Learning a New Practical Skill Weekly",
    // Custom: يُترك للمستخدم اختيار المهارة العملية المناسبة كل أسبوع
    description_ar: "تخصيص وقت أسبوعي لتعلم مهارة عملية صغيرة ومفيدة في الحياة اليومية",
    description_en: "Dedicate weekly time to learning a small, useful practical skill for daily life",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { intelligence: 2, creativity: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🔧",
    tags: ["مهارات عملية", "تطبيق", "أسبوعي"],
    motivationalQuotes: [
      "المهارة العملية تخدمك في الحياة أكثر من المعرفة النظرية وحدها",
      "مهارة جديدة كل أسبوع، توسّع قدرتك على حل المشكلات",
      "من تعلم بيديه، رسخ ما تعلمه بعقله",
    ],
  },
  {
    id: "learning_weekly_intellectual_discussion",
    title_ar: "المشاركة في نقاش فكري أسبوعي",
    title_en: "Weekly Intellectual Discussion",
    // Custom: يُترك للمستخدم اختيار المجموعة أو الشخص المناسب للنقاش أسبوعيًا
    description_ar: "المشاركة أسبوعيًا في نقاش فكري جاد مع أشخاص يحفزون تفكيرك",
    description_en: "Participate weekly in a serious intellectual discussion with people who challenge your thinking",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { wisdom: 3, influence: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "💬",
    tags: ["نقاش", "تفكير", "أسبوعي"],
    motivationalQuotes: [
      "النقاش الجاد يصقل الفكرة أكثر من التأمل المنفرد",
      "من ناقش أفكاره، اكتشف زوايا لم يرها وحده",
      "الحوار الفكري المنتظم، مدرسة مستمرة لا تنتهي",
    ],
  },
  {
    id: "learning_memory_techniques",
    title_ar: "تمارين تقنيات الذاكرة",
    title_en: "Memory Technique Exercises",
    description_ar: "ممارسة تقنيات تحسين الذاكرة كالربط الذهني أو قصور الذاكرة",
    description_en: "Practice memory improvement techniques such as mental association or memory palaces",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { intelligence: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🧩",
    tags: ["ذاكرة", "تدريب ذهني", "يومي"],
    motivationalQuotes: [
      "الذاكرة مهارة تُدرَّب، لا موهبة ثابتة",
      "تقنيات بسيطة، قدرة استيعاب أكبر بكثير",
      "من درّب ذاكرته، استعاد المعلومات بسهولة أكبر",
    ],
  },
  {
    id: "learning_weekly_deep_question",
    title_ar: "البحث العميق عن إجابة سؤال أسبوعيًا",
    title_en: "Deep Weekly Research on a Question",
    // Custom: يُترك للمستخدم اختيار السؤال المناسب للبحث كل أسبوع
    description_ar: "اختيار سؤال يثير فضولك والبحث المتعمق عن إجابته خلال الأسبوع",
    description_en: "Choose a question that sparks your curiosity and research it deeply over the week",
    category: "learning",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { intelligence: 3, wisdom: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🔬",
    tags: ["بحث", "استكشاف", "أسبوعي"],
    motivationalQuotes: [
      "سؤال واحد بعمق، أنفع من عشرة أسئلة سطحية",
      "البحث المتأني يكشف تفاصيل يغفلها الاستعجال",
      "من بحث بعمق، وصل لفهم لا يصل إليه القارئ العابر",
    ],
  },

  // ===== Advanced (minLevel 35, xp 35-50) =====
  {
    id: "learning_two_books_monthly",
    title_ar: "قراءة كتابين شهريًا",
    title_en: "Reading Two Books Monthly",
    // Custom: يُترك للمستخدم اختيار الكتابين المناسبين كل شهر
    description_ar: "رفع وتيرة القراءة لإنهاء كتابين متنوعين كل شهر",
    description_en: "Increase reading pace to finish two varied books each month",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 44,
    statsBoost: { intelligence: 5, discipline: 2 },
    frequency: "custom",
    suggestedTime: "morning",
    estimatedMinutes: 40,
    icon: "📖",
    tags: ["قراءة", "كتب", "متقدم"],
    motivationalQuotes: [
      "أربعة وعشرون كتابًا سنويًا، عقل يتغذى باستمرار",
      "لا يزال العبد في طلب العلم ما دام يقرأ ويتدبر",
      "من قرأ بكثافة، فكّر بعمق أكبر",
    ],
  },
  {
    id: "learning_teach_what_you_learn",
    title_ar: "تعليم ما تتعلمه للآخرين",
    title_en: "Teaching Others What You Learn",
    // Custom: يُترك للمستخدم اختيار الشخص والوقت المناسب أسبوعيًا
    description_ar: "مشاركة أسبوعية لما تعلمته مع شخص آخر بطريقة مبسطة",
    description_en: "Weekly sharing of what you've learned with someone else in a simplified way",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { influence: 4, wisdom: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "👨‍🏫",
    tags: ["تعليم", "مشاركة", "أسبوعي"],
    motivationalQuotes: [
      "خير الناس أنفعهم للناس، وتعليمهم من أعظم النفع",
      "من علّم غيره، ثبّت معرفته في نفسه أولاً",
      "المعرفة التي تُشارَك، تنمو ولا تنقص",
    ],
  },
  {
    id: "learning_build_second_brain",
    title_ar: "بناء نظام معرفة شخصي (Second Brain)",
    title_en: "Building a Personal Knowledge System (Second Brain)",
    description_ar: "تطوير وصيانة نظام رقمي يجمع كل ما تتعلمه بطريقة قابلة للبحث والربط",
    description_en: "Develop and maintain a digital system that captures everything you learn in a searchable, linked way",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { wisdom: 4, creativity: 2 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 20,
    icon: "🧠",
    tags: ["نظام معرفي", "تنظيم", "يومي"],
    motivationalQuotes: [
      "عقل ثانٍ رقمي، يحفظ ما ينساه عقلك الأول",
      "من قيّد علمه، كان كمن استعان على حفظه بأمانة الكتابة",
      "من بنى نظامه المعرفي، استرجع أفكاره القديمة بسهولة",
    ],
  },
  {
    id: "learning_monthly_research_summary",
    title_ar: "كتابة ملخص بحثي شهري",
    title_en: "Monthly Research Summary Writing",
    // Custom: يُترك للمستخدم اختيار الموضوع البحثي المناسب كل شهر
    description_ar: "اختيار موضوع والبحث فيه بعمق، ثم كتابة ملخص بحثي شهري عنه",
    description_en: "Choose a topic, research it in depth, then write a monthly research summary about it",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 45,
    statsBoost: { intelligence: 5, wisdom: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "📄",
    tags: ["بحث", "كتابة", "شهري"],
    motivationalQuotes: [
      "البحث المنظم يحوّل الفضول إلى معرفة موثقة",
      "ملخص بحثي واحد شهريًا، عمق معرفي يتراكم بسرعة",
      "من وثّق بحثه، أفاد نفسه وربما أفاد غيره لاحقًا",
    ],
  },
  {
    id: "learning_weekly_creative_writing",
    title_ar: "كتابة إبداعية أسبوعية",
    title_en: "Weekly Creative Writing",
    // Custom: يُترك للمستخدم اختيار نوع الكتابة الإبداعية المناسب أسبوعيًا
    description_ar: "تخصيص وقت أسبوعي لكتابة إبداعية حرة، قصة أو مقال أو شعر",
    description_en: "Dedicate weekly time to free creative writing — a story, essay, or poem",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { creativity: 5 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 45,
    icon: "✒️",
    tags: ["كتابة إبداعية", "تعبير", "أسبوعي"],
    motivationalQuotes: [
      "الكتابة الإبداعية تحرر الخيال من قيود الروتين",
      "قلم يكتب بحرية، أفكار تتدفق دون حدود",
      "من كتب بانتظام، طوّر صوته الخاص بمرور الوقت",
    ],
  },
  {
    id: "learning_monthly_new_field",
    title_ar: "استكشاف مجال معرفي جديد شهريًا",
    title_en: "Exploring a New Knowledge Field Monthly",
    // Custom: يُترك للمستخدم اختيار المجال الجديد المناسب كل شهر
    description_ar: "تخصيص وقت شهري للتعرف على أساسيات مجال معرفي لم تستكشفه من قبل",
    description_en: "Dedicate monthly time to learning the basics of a knowledge field you haven't explored before",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { intelligence: 4, creativity: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🧭",
    tags: ["استكشاف", "تنوع معرفي", "شهري"],
    motivationalQuotes: [
      "الاتساع المعرفي يخلق روابط لا يراها المتخصص الضيق",
      "مجال جديد كل شهر، أفق يتوسع باستمرار",
      "طلب العلم لا يقتصر على باب واحد، فمن اتسعت معرفته اتسع نفعه",
    ],
  },
  {
    id: "learning_critical_thinking_in_decisions",
    title_ar: "تطبيق التفكير النقدي في القرارات اليومية",
    title_en: "Applying Critical Thinking to Daily Decisions",
    description_ar: "مراجعة قراراتك اليومية بوعي، متسائلًا عن الافتراضات والأدلة قبل الاستنتاج",
    description_en: "Mindfully review your daily decisions, questioning assumptions and evidence before concluding",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { wisdom: 4, intelligence: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "⚖️",
    tags: ["تفكير نقدي", "قرارات", "يومي"],
    motivationalQuotes: [
      "القرار المدروس يوفر ندمًا لاحقًا كثيرًا",
      "التساؤل عن افتراضاتك، بداية كل فهم أعمق",
      "من فكّر نقديًا في صغائر قراراته، أتقن كبيرها",
    ],
  },
  {
    id: "learning_monthly_workshop",
    title_ar: "حضور ورشة عمل أو ندوة شهريًا",
    title_en: "Attending a Workshop or Seminar Monthly",
    // Custom: يُترك للمستخدم اختيار الورشة المناسبة لاهتماماته كل شهر
    description_ar: "المشاركة الشهرية في ورشة عمل أو ندوة تطوّر معرفتك أو مهاراتك",
    description_en: "Monthly participation in a workshop or seminar that develops your knowledge or skills",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { intelligence: 3, influence: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🏛️",
    tags: ["ورشة عمل", "تعلم مباشر", "شهري"],
    motivationalQuotes: [
      "التعلم التفاعلي يرسخ المعرفة أكثر من القراءة وحدها",
      "ورشة واحدة شهريًا، شبكة معرفية وعملية تتوسع",
      "من تعلم من الخبراء مباشرة، اختصر سنوات من التجربة الفردية",
    ],
  },
  {
    id: "learning_advanced_language_practice",
    title_ar: "تعلم لغة جديدة بمستوى متقدم",
    title_en: "Advanced-Level New Language Learning",
    description_ar: "الانتقال من أساسيات اللغة إلى ممارسة متقدمة كالقراءة والمحادثة الحرة",
    description_en: "Move from language basics to advanced practice such as reading and free conversation",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { intelligence: 4, discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🌍",
    tags: ["لغة", "متقدم", "يومي"],
    motivationalQuotes: [
      "الطلاقة تأتي بعد صبر طويل من الممارسة المستمرة",
      "لغة جديدة، نافذة على ثقافة وطريقة تفكير مختلفة",
      "من أتقن لغة جديدة، وسّع عالمه بأكمله",
    ],
  },
  {
    id: "learning_weekly_progress_documentation",
    title_ar: "توثيق رحلة التعلم أسبوعيًا",
    title_en: "Weekly Learning Journey Documentation",
    // Custom: يُترك للمستخدم تحديد يوم أسبوعي ثابت للتوثيق
    description_ar: "تدوين أسبوعي لما تعلمته والتحديات التي واجهتها في رحلة تطورك المعرفي",
    description_en: "Weekly documentation of what you've learned and the challenges faced in your learning journey",
    category: "learning",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { wisdom: 3, discipline: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 20,
    icon: "🧾",
    tags: ["توثيق", "تقدم", "أسبوعي"],
    motivationalQuotes: [
      "التوثيق يكشف تقدمًا لا تراه في زحمة الأيام",
      "من راجع رحلته، عرف أين يستحق أن يستمر أو يعدّل",
      "سجل التعلم شاهد صادق على مسيرتك الطويلة",
    ],
  },

  // ===== Expert (minLevel 60, xp 50-80) =====
  {
    id: "learning_author_book_or_course",
    title_ar: "تأليف كتاب أو دورة تعليمية",
    title_en: "Authoring a Book or Educational Course",
    // Custom: يُترك للمستخدم تحديد وتيرة العمل على المشروع طويل المدى
    description_ar: "العمل المنتظم على تأليف كتاب أو دورة تعليمية توثّق خبرتك المتراكمة",
    description_en: "Regular work on authoring a book or educational course that documents your accumulated expertise",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 75,
    statsBoost: { creativity: 5, wisdom: 4 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 60,
    icon: "📘",
    tags: ["تأليف", "أثر معرفي", "خبير"],
    motivationalQuotes: [
      "العمل الذي يُنشر، يعلّم من لا تلتقيه أبدًا",
      "خبرة سنوات، موثّقة في عمل واحد يصل لآلاف",
      "من صبر على مشروع معرفي طويل، ترك أثرًا يفوق عمره",
    ],
  },
  {
    id: "learning_teach_regularly",
    title_ar: "التدريس بانتظام",
    title_en: "Teaching Regularly",
    // Custom: يُترك للمستخدم تحديد جهة التدريس والجدول المناسب
    description_ar: "تخصيص وقت منتظم لتدريس ما تتقنه لمجموعة من المتعلمين",
    description_en: "Dedicate regular time to teaching what you've mastered to a group of learners",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 65,
    statsBoost: { influence: 5, wisdom: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🎤",
    tags: ["تدريس", "تعليم", "أثر"],
    motivationalQuotes: [
      "لا يزال العالِم عالِمًا ما دام يتعلم ويعلّم",
      "من علّم بانتظام، ضاعف أثره في كل من تتلمذ عليه",
      "التدريس أفضل طريقة لإتقان ما تعرفه حقًا",
    ],
  },
  {
    id: "learning_build_educational_courses",
    title_ar: "بناء دورات تعليمية للآخرين",
    title_en: "Building Educational Courses for Others",
    // Custom: يُترك للمستخدم تحديد محتوى ووتيرة الدورات
    description_ar: "تصميم وإنتاج دورات تعليمية منظمة تنقل خبرتك لجمهور أوسع",
    description_en: "Design and produce structured educational courses that share your expertise with a wider audience",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 68,
    statsBoost: { creativity: 4, influence: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🖥️",
    tags: ["دورات", "إنتاج تعليمي", "خبير"],
    motivationalQuotes: [
      "دورة واحدة مصممة بعناية، تصل لمن لا تلتقيهم أبدًا",
      "من نظّم معرفته في دورة، ضاعف قابليتها للانتشار",
      "الإنتاج التعليمي المتقن، إرث معرفي يبقى بعدك",
    ],
  },
  {
    id: "learning_podcasting_blogging",
    title_ar: "إنتاج محتوى تعليمي (بودكاست أو مدونة)",
    title_en: "Producing Educational Content (Podcast or Blog)",
    // Custom: يُترك للمستخدم تحديد الوسيلة والوتيرة المناسبة
    description_ar: "إنتاج محتوى منتظم عبر بودكاست أو مدونة يشارك معرفتك مع جمهور متابع",
    description_en: "Produce regular content via podcast or blog that shares your knowledge with a following audience",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 62,
    statsBoost: { creativity: 4, influence: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🎙️",
    tags: ["بودكاست", "مدونة", "محتوى"],
    motivationalQuotes: [
      "المحتوى المنتظم يبني حضورًا لا يبنيه محتوى نادر",
      "صوتك أو كتابتك، قد تصل لمن لم يلتقِ بك يومًا",
      "من واظب على النشر، بنى جمهورًا يثق بمعرفته",
    ],
  },
  {
    id: "learning_annual_knowledge_review",
    title_ar: "مراجعة سنوية شاملة للمعرفة",
    title_en: "Annual Comprehensive Knowledge Review",
    // Custom: يُترك للمستخدم تحديد الوقت المناسب سنويًا لهذه المراجعة الشاملة
    description_ar: "جلسة سنوية لمراجعة كل ما تعلمته وتحديد فجوات المعرفة القادمة",
    description_en: "An annual session to review everything learned and identify upcoming knowledge gaps",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 55,
    statsBoost: { wisdom: 6 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🗓️",
    tags: ["مراجعة سنوية", "تخطيط معرفي", "خبير"],
    motivationalQuotes: [
      "من راجع سنته المعرفية، خطط لعام أكثر عمقًا",
      "خير الناس أنفعهم للناس، ومراجعة معرفتك تزيد نفعك بها لغيرك",
      "معرفة بلا مراجعة دورية، تتوقف عن التطور",
    ],
  },
  {
    id: "learning_master_new_language_fully",
    title_ar: "إتقان لغة جديدة كاملة",
    title_en: "Fully Mastering a New Language",
    // Custom: يُترك للمستخدم تحديد وتيرة الممارسة المكثفة المناسبة
    description_ar: "الوصول لمستوى إتقان كامل في لغة جديدة عبر ممارسة مكثفة ومستمرة",
    description_en: "Reach full mastery in a new language through intensive, sustained practice",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 70,
    statsBoost: { intelligence: 6, discipline: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🏆",
    tags: ["لغة", "إتقان", "خبير"],
    motivationalQuotes: [
      "الإتقان الكامل ثمرة سنوات من الممارسة الصبورة",
      "لغة متقنة، جسر حقيقي لعالم وثقافة جديدين",
      "من وصل للإتقان، فتح أبوابًا لم تكن متاحة من قبل",
    ],
  },
  {
    id: "learning_contribute_to_research",
    title_ar: "المساهمة في بحث علمي أو معرفي",
    title_en: "Contributing to Scientific or Knowledge-Based Research",
    // Custom: يُترك للمستخدم تحديد مجال ووتيرة المساهمة البحثية
    description_ar: "المشاركة الفعلية في مشروع بحثي يضيف قيمة معرفية حقيقية لمجالك",
    description_en: "Actively participate in a research project that adds real knowledge value to your field",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 72,
    statsBoost: { intelligence: 5, wisdom: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🔭",
    tags: ["بحث علمي", "مساهمة", "خبير"],
    motivationalQuotes: [
      "المساهمة البحثية توسّع حدود المعرفة الإنسانية، لا معرفتك فقط",
      "من ساهم في بحث حقيقي، ترك بصمة تتجاوز اسمه",
      "من سلك طريقًا يبتغي فيه علمًا نافعًا للناس، فقد سلك طريق الخير",
    ],
  },
  {
    id: "learning_mentor_beginner_researchers",
    title_ar: "إرشاد باحثين مبتدئين",
    title_en: "Mentoring Beginner Researchers",
    // Custom: يُترك للمستخدم تحديد الأشخاص والوتيرة المناسبة
    description_ar: "تخصيص وقت منتظم لإرشاد من هم في بداية رحلتهم البحثية أو المعرفية",
    description_en: "Dedicate regular time to guiding those at the beginning of their research or learning journey",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { compassion: 4, influence: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🧑‍🔬",
    tags: ["إرشاد", "بحث", "خبير"],
    motivationalQuotes: [
      "من أرشد باحثًا مبتدئًا، اختصر له سنوات من التخبط",
      "التوجيه الصادق للمبتدئين، استثمار في مستقبل المعرفة",
      "أعظم الباحثين كان لهم من أرشدهم في البداية",
    ],
  },
  {
    id: "learning_design_complete_curriculum",
    title_ar: "تصميم منهج تعليمي متكامل",
    title_en: "Designing a Complete Educational Curriculum",
    // Custom: يُترك للمستخدم تحديد نطاق ووتيرة العمل على المنهج
    description_ar: "بناء منهج تعليمي شامل ومتسلسل ينقل مجالًا معرفيًا كاملاً بطريقة منظمة",
    description_en: "Build a comprehensive, sequenced curriculum that conveys an entire knowledge field in an organized way",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 66,
    statsBoost: { wisdom: 5, creativity: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🏗️",
    tags: ["منهج تعليمي", "تصميم", "خبير"],
    motivationalQuotes: [
      "المنهج المتقن يختصر لغيرك طريقًا استغرقك سنوات",
      "من صمم منهجًا واضحًا، نظّم فوضى معرفية لصالح آخرين",
      "التعليم المنظم أثر يمتد لأجيال من المتعلمين",
    ],
  },
  {
    id: "learning_lead_learning_community",
    title_ar: "قيادة مجتمع تعليمي",
    title_en: "Leading a Learning Community",
    // Custom: يُترك للمستخدم تحديد طبيعة المجتمع ووتيرة الأنشطة
    description_ar: "إنشاء ورعاية مجتمع من المتعلمين يتشاركون هدفًا معرفيًا مشتركًا",
    description_en: "Create and nurture a community of learners sharing a common educational goal",
    category: "learning",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { influence: 5, compassion: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🌐",
    tags: ["مجتمع تعليمي", "قيادة", "خبير"],
    motivationalQuotes: [
      "مجتمع التعلم الجماعي يضاعف أثر المعرفة الفردية",
      "من دلّ على خير فله مثل أجر فاعله، وقيادة مجتمع علم دلالة مستمرة",
      "التعلم الجماعي يخلق دافعًا لا يوفره التعلم المنفرد",
    ],
  },
];
