import type { HabitTemplate } from "../types";

/**
 * 40 spiritual/religious habits, 10 per difficulty tier, covering mainstream
 * Islamic practices (adhkar, Qur'an, prayer, charity, character). Avoids
 * sect-specific or contested practices; motivational lines are phrased as
 * general encouragement rather than verbatim hadith citations to avoid
 * misattribution risk.
 */
export const spiritualHabits: HabitTemplate[] = [
  // ===== Beginner (minLevel 1, xp 10-20) =====
  {
    id: "spiritual_morning_azkar",
    title_ar: "أذكار الصباح",
    title_en: "Morning Remembrance",
    description_ar: "قراءة أذكار الصباح كاملة بعد صلاة الفجر لحماية يومك وبركته",
    description_en: "Complete morning remembrance after Fajr prayer",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 15,
    statsBoost: { spirit: 3, discipline: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 15,
    icon: "🌅",
    tags: ["أذكار", "صباح", "روحاني", "يومي"],
    motivationalQuotes: [
      "بدأت يومك بذكر الله، فأنت في حصن منيع",
      "الأذكار درع يرافقك في كل خطوة اليوم",
      "من أحسن استقبال يومه بالذكر، بورك له فيه",
    ],
  },
  {
    id: "spiritual_evening_azkar",
    title_ar: "أذكار المساء",
    title_en: "Evening Remembrance",
    description_ar: "قراءة أذكار المساء بعد صلاة العصر أو المغرب لختم يومك بالطمأنينة",
    description_en: "Complete evening remembrance after Asr or Maghrib prayer",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 15,
    statsBoost: { spirit: 3, discipline: 1 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 15,
    icon: "🌆",
    tags: ["أذكار", "مساء", "روحاني", "يومي"],
    motivationalQuotes: [
      "اختم يومك كما بدأته — بذكر يطمئن القلب",
      "أذكار المساء سكينة قبل الليل",
      "كل يوم يستحق أن يُختم بالشكر",
    ],
  },
  {
    id: "spiritual_daily_quran_page",
    title_ar: "قراءة صفحة من القرآن",
    title_en: "Read a Page of Qur'an",
    description_ar: "خصّص وقتًا يوميًا لقراءة صفحة واحدة على الأقل من القرآن الكريم",
    description_en: "Read at least one page of the Qur'an daily",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { spirit: 2, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "📖",
    tags: ["قرآن", "قراءة", "يومي"],
    motivationalQuotes: [
      "صفحة واحدة كل يوم تصنع ختمة كل عام",
      "القليل الدائم خير من الكثير المنقطع",
      "كل حرف تقرأه له أجره الخاص",
    ],
  },
  {
    id: "spiritual_night_dua",
    title_ar: "دعاء قبل النوم",
    title_en: "Bedtime Supplication",
    description_ar: "قراءة أدعية النوم المأثورة قبل الخلود للراحة",
    description_en: "Recite the sunnah supplications before sleeping",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { spirit: 2 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 5,
    icon: "🌙",
    tags: ["دعاء", "نوم", "يومي"],
    motivationalQuotes: [
      "نم وأنت في ذمة الله",
      "آخر كلامك قبل النوم، اجعله ذكرًا",
      "دعاء صغير يمنحك نومًا هادئًا",
    ],
  },
  {
    id: "spiritual_istighfar",
    title_ar: "الاستغفار المتكرر",
    title_en: "Repeated Seeking of Forgiveness",
    description_ar: "قول أستغفر الله مئة مرة موزعة على اليوم",
    description_en: "Say astaghfirullah 100 times throughout the day",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { spirit: 2, discipline: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🤲",
    tags: ["استغفار", "ذكر", "يومي"],
    motivationalQuotes: [
      "الاستغفار يفتح أبوابًا لم تكن تتوقعها",
      "كل استغفار محو لأثر ذنب",
      "قلب يستغفر، قلب يتجدد",
    ],
  },
  {
    id: "spiritual_weekly_family_call",
    title_ar: "صلة الرحم الأسبوعية",
    title_en: "Weekly Family Connection",
    description_ar: "اتصال أو زيارة لأحد الأقارب كل أسبوع للحفاظ على الروابط",
    description_en: "Call or visit a relative each week to maintain family ties",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 18,
    statsBoost: { compassion: 3, influence: 1 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "👨‍👩‍👧",
    tags: ["صلة رحم", "أسرة", "أسبوعي"],
    motivationalQuotes: [
      "صلة الرحم تزيد في العمر والبركة",
      "اتصال بسيط قد يُدخل السرور على قلب",
      "الأرحام أمانة، لا تتركها تبرد",
    ],
  },
  {
    id: "spiritual_daily_sadaqah",
    title_ar: "الصدقة اليومية ولو يسيرة",
    title_en: "Daily Charity, However Small",
    description_ar: "التصدق بأي مبلغ يومي مهما كان صغيرًا، عادة قبل أن تكون مبلغًا",
    description_en: "Give any small amount in charity daily, as a habit more than an amount",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 14,
    statsBoost: { compassion: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🪙",
    tags: ["صدقة", "عطاء", "يومي"],
    motivationalQuotes: [
      "الصدقة لا تنقص المال، بل تباركه",
      "يد تعطي، خير من يد تأخذ",
      "أقل القليل قد يكون أعظم الأجر",
    ],
  },
  {
    id: "spiritual_post_prayer_tasbeeh",
    title_ar: "تسبيح ما بعد الصلاة",
    title_en: "Post-Prayer Glorification",
    description_ar: "المحافظة على التسبيح والتحميد والتكبير بعد كل صلاة مفروضة",
    description_en: "Maintain the tasbeeh routine after each obligatory prayer",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { spirit: 2, discipline: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "📿",
    tags: ["تسبيح", "صلاة", "يومي"],
    motivationalQuotes: [
      "دقائق بعد كل صلاة تصنع فرقًا كبيرًا",
      "التسبيح زاد خفيف على اللسان، ثقيل في الميزان",
      "خمس مرات يوميًا، عادة تُبنى بثبات",
    ],
  },
  {
    id: "spiritual_wudu_before_sleep",
    title_ar: "الوضوء قبل النوم",
    title_en: "Ablution Before Sleep",
    description_ar: "المحافظة على الوضوء قبل الخلود للنوم كسنة نبوية",
    description_en: "Maintain ablution before going to sleep as a prophetic practice",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 2, spirit: 1 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 5,
    icon: "💧",
    tags: ["وضوء", "نوم", "يومي"],
    motivationalQuotes: [
      "طهارة الجسد تسبق طهارة القلب",
      "عادة صغيرة، أثرها يمتد لليوم التالي",
      "نم طاهرًا، تستيقظ خفيفًا",
    ],
  },
  {
    id: "spiritual_memorize_verse",
    title_ar: "حفظ آية جديدة يوميًا",
    title_en: "Memorize a New Verse Daily",
    description_ar: "حفظ آية واحدة جديدة كل يوم مع مراجعة ما سبق حفظه",
    description_en: "Memorize one new verse daily while reviewing prior memorization",
    category: "spiritual",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 16,
    statsBoost: { intelligence: 2, spirit: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🧠",
    tags: ["حفظ", "قرآن", "يومي"],
    motivationalQuotes: [
      "آية اليوم، أساس لحفظ الغد",
      "الحفظ التدريجي أثبت من الحفظ السريع",
      "كل آية تحفظها كنز لا يُسرق",
    ],
  },

  // ===== Intermediate (minLevel 15, xp 20-35) =====
  {
    id: "spiritual_qiyam_two_rakat",
    title_ar: "قيام الليل (ولو ركعتين)",
    title_en: "Night Prayer (Even Two Rak'ahs)",
    description_ar: "الاستيقاظ لأداء ركعتين على الأقل من قيام الليل قبل الفجر",
    description_en: "Wake up to pray at least two rak'ahs of night prayer before Fajr",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { spirit: 4, discipline: 2 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 15,
    icon: "🌌",
    tags: ["قيام", "ليل", "صلاة"],
    motivationalQuotes: [
      "ثلث الليل الأخير، ساعة يُفتح فيها الباب",
      "ركعتان في السكون، تعدلان الكثير في الزحام",
      "من قام قليلاً بثبات، خير ممن قام كثيرًا وانقطع",
    ],
  },
  {
    id: "spiritual_monday_thursday_fasting",
    title_ar: "صيام الاثنين والخميس",
    title_en: "Monday & Thursday Fasting",
    description_ar: "صيام يومي الاثنين والخميس من كل أسبوع اقتداءً بالسنة",
    description_en: "Fast on Mondays and Thursdays each week",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 30,
    statsBoost: { discipline: 4, spirit: 2 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 0,
    icon: "🌗",
    tags: ["صيام", "سنة", "أسبوعي"],
    motivationalQuotes: [
      "يومان في الأسبوع، عادة تُهذّب النفس",
      "الصيام مدرسة للصبر تتكرر كل أسبوع",
      "جوع مؤقت، صفاء يدوم",
    ],
  },
  {
    id: "spiritual_memorize_short_surah",
    title_ar: "حفظ سورة قصيرة",
    title_en: "Memorize a Short Surah",
    description_ar: "حفظ سورة كاملة من قصار السور خلال أسبوعين مع المراجعة اليومية",
    description_en: "Memorize a complete short surah over two weeks with daily review",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 25,
    statsBoost: { intelligence: 3, spirit: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "📗",
    tags: ["حفظ", "سورة", "قرآن"],
    motivationalQuotes: [
      "سورة كاملة تُضاف لرصيدك مع الله",
      "الحفظ المنظم يثمر أسرع مما تتوقع",
      "كل سورة تحفظها، تلازمك في صلاتك",
    ],
  },
  {
    id: "spiritual_dua_for_ten",
    title_ar: "الدعاء لعشرة أشخاص",
    title_en: "Supplicate for Ten People",
    description_ar: "الدعاء يوميًا لعشرة أشخاص من أهلك وأصدقائك بظهر الغيب",
    description_en: "Pray daily for ten people, family or friends, without their knowledge",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 20,
    statsBoost: { compassion: 4, spirit: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "💌",
    tags: ["دعاء", "غيب", "رحمة"],
    motivationalQuotes: [
      "دعاؤك لأخيك بظهر الغيب، يعود عليك",
      "قلب يدعو لغيره، قلب واسع",
      "لا تعرف أي دعوة منها مستجابة، فأكثر منها",
    ],
  },
  {
    id: "spiritual_tadabbur_session",
    title_ar: "تلاوة بتدبر (30 دقيقة)",
    title_en: "Reflective Recitation (30 Minutes)",
    description_ar: "جلسة يومية لتلاوة القرآن مع التدبر في المعاني وليس فقط سرعة القراءة",
    description_en: "A daily session reciting the Qur'an with reflection on meaning, not just pace",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 25,
    statsBoost: { wisdom: 3, spirit: 2 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 30,
    icon: "🕊️",
    tags: ["تدبر", "قرآن", "تأمل"],
    motivationalQuotes: [
      "التدبر يحوّل القراءة إلى فهم",
      "آية واحدة بتدبر، تعدل صفحات بلا تأمل",
      "اقرأ ببطء، فالمعنى لا يُستعجل",
    ],
  },
  {
    id: "spiritual_duha_prayer",
    title_ar: "صلاة الضحى",
    title_en: "Duha (Forenoon) Prayer",
    description_ar: "أداء ركعتين أو أكثر من صلاة الضحى في منتصف الصباح",
    description_en: "Pray two or more rak'ahs of Duha in mid-morning",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 20,
    statsBoost: { spirit: 3, discipline: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 10,
    icon: "☀️",
    tags: ["صلاة", "ضحى", "نافلة"],
    motivationalQuotes: [
      "استراحة قصيرة مع الله وسط انشغال يومك",
      "ركعتان تكفيان عن صدقة كل مفصل في جسدك",
      "الضحى وقفة نور في منتصف النهار",
    ],
  },
  {
    id: "spiritual_sunnah_rawatib",
    title_ar: "المحافظة على السنن الرواتب",
    title_en: "Maintaining the Regular Sunnah Prayers",
    description_ar: "أداء السنن الرواتب المرتبطة بالصلوات المفروضة يوميًا",
    description_en: "Perform the regular sunnah prayers attached to the obligatory prayers daily",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { discipline: 3, spirit: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "🕌",
    tags: ["سنن", "صلاة", "انضباط"],
    motivationalQuotes: [
      "بيت في الجنة يُبنى بمحافظة يومية",
      "النوافل تجبر ما قد ينقص من الفرائض",
      "الثبات على القليل خير من التذبذب في الكثير",
    ],
  },
  {
    id: "spiritual_weekly_knowledge_circle",
    title_ar: "مجلس علم أسبوعي",
    title_en: "Weekly Knowledge Circle",
    description_ar: "حضور أو متابعة درس علمي شرعي واحد أسبوعيًا لطلب العلم",
    description_en: "Attend or follow one religious knowledge session weekly",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { wisdom: 4, intelligence: 1 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🎓",
    tags: ["علم", "تعلم", "أسبوعي"],
    motivationalQuotes: [
      "طلب العلم رفيق العمر كله",
      "درس واحد أسبوعيًا يبني قاعدة علمية متينة",
      "العلم النافع نور يهدي في الحياة",
    ],
  },
  {
    id: "spiritual_gratitude_journal",
    title_ar: "يوميات شكر لله",
    title_en: "Gratitude Journal to God",
    description_ar: "كتابة ثلاث نعم يوميًا تشكر الله عليها لتعزيز الرضا والامتنان",
    description_en: "Write three blessings daily to thank God for, fostering contentment",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 20,
    statsBoost: { spirit: 2, wisdom: 2 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "📝",
    tags: ["شكر", "امتنان", "كتابة"],
    motivationalQuotes: [
      "من شكر القليل، استحق المزيد",
      "النعم كثيرة، والعين على ما ينقص",
      "الشكر المكتوب يبقى أثره أطول",
    ],
  },
  {
    id: "spiritual_feed_someone",
    title_ar: "إطعام محتاج أو صائم",
    title_en: "Feeding Someone in Need",
    description_ar: "المساهمة في إطعام محتاج أو تفطير صائم مرة كل أسبوع",
    description_en: "Contribute to feeding someone in need or breaking a faster's fast weekly",
    category: "spiritual",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { compassion: 4 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🍽️",
    tags: ["إطعام", "صدقة", "أسبوعي"],
    motivationalQuotes: [
      "من فطّر صائمًا، شارك في أجره",
      "الطعام الذي تشاركه يعود إليك بركة",
      "لقمة تسد جوعًا، قد تُشبع قلبًا",
    ],
  },

  // ===== Advanced (minLevel 35, xp 35-50) =====
  {
    id: "spiritual_weekly_juz_completion",
    title_ar: "ختم جزء من القرآن أسبوعيًا",
    title_en: "Completing a Juz Weekly",
    description_ar: "قراءة جزء كامل من القرآن موزعًا على أيام الأسبوع",
    description_en: "Read a complete juz (Qur'an section) spread across the week",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { spirit: 4, discipline: 3 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "📚",
    tags: ["قرآن", "ختمة", "أسبوعي"],
    motivationalQuotes: [
      "جزء كل أسبوع، ختمة كل سبعة أشهر تقريبًا",
      "التوزيع المنتظم يجعل الختم يسيرًا",
      "كل جزء تقرأه خطوة نحو ختمة كاملة",
    ],
  },
  {
    id: "spiritual_nightly_qiyam",
    title_ar: "قيام الليل بانتظام",
    title_en: "Regular Night Prayer",
    description_ar: "المحافظة على قيام الليل كل ليلة، ولو بركعات قليلة",
    description_en: "Maintain night prayer every night, even with few rak'ahs",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 45,
    statsBoost: { spirit: 5, discipline: 3 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 20,
    icon: "🌃",
    tags: ["قيام", "انتظام", "ليل"],
    motivationalQuotes: [
      "من اعتاد قيام الليل، افتقده إن تركه",
      "السكون في جوف الليل، فرصة لا تعوض",
      "المداومة سر الثبات على هذه العبادة",
    ],
  },
  {
    id: "spiritual_three_days_monthly_fasting",
    title_ar: "صيام ثلاثة أيام من كل شهر",
    title_en: "Fasting Three Days Every Month",
    description_ar: "صيام ثلاثة أيام في كل شهر هجري كسنة مؤكدة",
    description_en: "Fast three days each lunar month as a confirmed sunnah",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { discipline: 4, spirit: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 0,
    icon: "🌒",
    tags: ["صيام", "شهري", "سنة"],
    motivationalQuotes: [
      "ثلاثة أيام تعدل صيام الدهر كله",
      "عادة شهرية بسيطة، أجرها عظيم",
      "الانضباط الشهري يبني نفسًا صابرة",
    ],
  },
  {
    id: "spiritual_complete_juz_amma",
    title_ar: "حفظ جزء عمّ كاملاً",
    title_en: "Memorizing Juz Amma Completely",
    description_ar: "المحافظة اليومية على حفظ ومراجعة جزء عمّ حتى إتمامه وثباته",
    description_en: "Daily commitment to memorizing and reviewing Juz Amma until mastered",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { intelligence: 4, spirit: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 25,
    icon: "📕",
    tags: ["حفظ", "جزء عم", "قرآن"],
    motivationalQuotes: [
      "جزء عم رصيد يرافقك في صلاتك طوال العمر",
      "الحفظ الثابت أفضل من الحفظ السريع المتزعزع",
      "كل يوم مراجعة، يقرّب الإتقان",
    ],
  },
  {
    id: "spiritual_teach_others",
    title_ar: "تعليم الآخرين ما تعلمته",
    title_en: "Teaching Others What You Learned",
    description_ar: "تخصيص وقت أسبوعي لنقل معرفة دينية بسيطة لشخص آخر",
    description_en: "Dedicate weekly time to passing on simple religious knowledge to someone else",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { influence: 4, wisdom: 2 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "👨‍🏫",
    tags: ["تعليم", "دعوة", "أسبوعي"],
    motivationalQuotes: [
      "من علّم خيرًا، كان له مثل أجر من عمل به",
      "نقل المعرفة يضاعف نفعها",
      "كلمة طيبة تُعلّمها، قد تغيّر مسار شخص",
    ],
  },
  {
    id: "spiritual_daily_good_word",
    title_ar: "نشر كلمة خير يوميًا",
    title_en: "Spreading a Good Word Daily",
    description_ar: "مشاركة نصيحة أو تذكير نافع يوميًا مع من حولك بأسلوب لطيف",
    description_en: "Share one beneficial reminder or piece of advice daily with kindness",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 35,
    statsBoost: { influence: 3, compassion: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "💬",
    tags: ["دعوة", "حكمة", "يومي"],
    motivationalQuotes: [
      "الكلمة الطيبة صدقة",
      "أوصل الخير كما وصلك، ولو بكلمة",
      "من دلّ على خير فله مثل أجر فاعله",
    ],
  },
  {
    id: "spiritual_review_memorization",
    title_ar: "مراجعة المحفوظ من القرآن",
    title_en: "Reviewing Qur'an Memorization",
    description_ar: "جلسة يومية منتظمة لمراجعة كل ما سبق حفظه وضمان ثباته",
    description_en: "A regular daily session reviewing all previously memorized portions",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { intelligence: 3, discipline: 3 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 20,
    icon: "🔁",
    tags: ["مراجعة", "حفظ", "قرآن"],
    motivationalQuotes: [
      "الحفظ بلا مراجعة كالماء في اليد المفتوحة",
      "مراجعة يومية قصيرة تحفظ سنوات من الجهد",
      "الثبات على المراجعة سر بقاء الحفظ",
    ],
  },
  {
    id: "spiritual_ongoing_charity",
    title_ar: "صدقة جارية مستمرة",
    title_en: "Ongoing Continuous Charity",
    description_ar: "المساهمة الشهرية في مشروع خيري مستمر الأثر مثل حفر بئر أو دعم تعليم",
    description_en: "Monthly contribution to an ongoing charitable project with lasting impact",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 45,
    statsBoost: { compassion: 5 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🌳",
    tags: ["صدقة جارية", "أثر", "شهري"],
    motivationalQuotes: [
      "عمل يستمر نفعه بعد انقطاعك عنه",
      "الصدقة الجارية استثمار لا ينتهي عائده",
      "زرعتها اليوم، وثمرها يبقى غدًا",
    ],
  },
  {
    id: "spiritual_distant_relatives",
    title_ar: "صلة الأرحام البعيدة",
    title_en: "Connecting with Distant Relatives",
    description_ar: "التواصل الشهري مع أقارب بعيدين قد يتم نسيانهم بمرور الوقت",
    description_en: "Monthly outreach to distant relatives who might otherwise be forgotten",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { compassion: 4, influence: 1 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "🌐",
    tags: ["صلة رحم", "أقارب", "شهري"],
    motivationalQuotes: [
      "الرحم البعيدة تستحق تذكرًا أيضًا",
      "لا تنسَ من قد ينساك الجميع",
      "خيط رحم رفيع، حافظ عليه من الانقطاع",
    ],
  },
  {
    id: "spiritual_reflect_names_of_god",
    title_ar: "تدبر أسماء الله الحسنى",
    title_en: "Reflecting on the Names of God",
    description_ar: "التأمل الأسبوعي في اسم واحد من أسماء الله الحسنى ومعناه في حياتك",
    description_en: "Weekly reflection on one of God's beautiful names and its meaning in your life",
    category: "spiritual",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 37,
    statsBoost: { wisdom: 4, spirit: 3 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "✨",
    tags: ["تدبر", "أسماء الله", "أسبوعي"],
    motivationalQuotes: [
      "معرفة الله تبدأ بمعرفة أسمائه",
      "اسم واحد بتأمل، يغيّر نظرتك للأسبوع كله",
      "أسماؤه الحسنى أبواب للطمأنينة",
    ],
  },

  // ===== Expert (minLevel 60, xp 50-80) =====
  {
    id: "spiritual_monthly_full_quran",
    title_ar: "ختم القرآن شهريًا",
    title_en: "Completing the Qur'an Monthly",
    description_ar: "المحافظة على قراءة يومية منتظمة تكفي لختم القرآن كل شهر",
    description_en: "Maintain a regular daily reading pace sufficient to complete the Qur'an monthly",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 65,
    statsBoost: { spirit: 6, discipline: 4 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 40,
    icon: "🕋",
    tags: ["ختمة", "شهري", "قرآن"],
    motivationalQuotes: [
      "ختمة كاملة كل شهر، رفيق دائم مع القرآن",
      "الانضباط اليومي يصنع إنجازًا شهريًا كبيرًا",
      "من لازم القرآن، لازمه في كل أحواله",
    ],
  },
  {
    id: "spiritual_extended_tahajjud",
    title_ar: "قيام الليل بتهجد طويل",
    title_en: "Extended Tahajjud Prayer",
    description_ar: "إطالة صلاة الليل بركعات وقراءة أطول للتقرب في وقت السحر",
    description_en: "Extending night prayer with longer rak'ahs and recitation before dawn",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 70,
    statsBoost: { spirit: 7, discipline: 4 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 45,
    icon: "🌠",
    tags: ["تهجد", "قيام", "سحر"],
    motivationalQuotes: [
      "وقت السحر ساعة استجابة لا تُضيَّع",
      "طول القيام دليل على حب القرب",
      "من جاهد نفسه في الليل، وجد راحتها في النهار",
    ],
  },
  {
    id: "spiritual_alternate_day_fasting",
    title_ar: "صيام يوم وإفطار يوم",
    title_en: "Alternate Day Fasting",
    description_ar: "المحافظة على نمط صيام يوم وإفطار يوم بانتظام",
    description_en: "Maintaining a consistent pattern of fasting every other day",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { discipline: 6, spirit: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 0,
    icon: "⚖️",
    tags: ["صيام", "انضباط", "متقدم"],
    motivationalQuotes: [
      "صبر متكرر يبني إرادة لا تلين",
      "من اعتاد الصيام، هان عليه كل جوع بعده",
      "نمط ثابت من الصبر، أثره في النفس عميق",
    ],
  },
  {
    id: "spiritual_teach_quran_regularly",
    title_ar: "تعليم القرآن للآخرين بانتظام",
    title_en: "Regularly Teaching Others the Qur'an",
    description_ar: "تخصيص جلسات أسبوعية منتظمة لتعليم القرآن أو تحفيظه لآخرين",
    description_en: "Dedicate regular weekly sessions to teaching or helping others memorize Qur'an",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 68,
    statsBoost: { influence: 5, wisdom: 3 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🕌",
    tags: ["تعليم", "قرآن", "دعوة"],
    motivationalQuotes: [
      "خيركم من تعلم القرآن وعلّمه",
      "بذرة تزرعها في قلب آخر، تثمر لسنوات",
      "علم تنشره، أجره يلحقك ولو غبت",
    ],
  },
  {
    id: "spiritual_regular_income_giving",
    title_ar: "الإنفاق المنتظم في سبيل الله",
    title_en: "Regular Giving for the Sake of God",
    description_ar: "تخصيص نسبة ثابتة من الدخل الشهري للإنفاق في وجوه الخير",
    description_en: "Allocating a fixed percentage of monthly income toward charitable giving",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 55,
    statsBoost: { compassion: 6 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "💰",
    tags: ["إنفاق", "صدقة", "شهري"],
    motivationalQuotes: [
      "ما نقص مال من صدقة",
      "الإنفاق المنتظم بركة تتجدد كل شهر",
      "من زرع في المال، حصد في القلب راحة",
    ],
  },
  {
    id: "spiritual_sponsor_orphan_family",
    title_ar: "كفالة يتيم أو أسرة محتاجة",
    title_en: "Sponsoring an Orphan or Needy Family",
    description_ar: "الالتزام الشهري بكفالة يتيم أو دعم أسرة تحتاج مساندة مستمرة",
    description_en: "Monthly commitment to sponsoring an orphan or supporting a family in need",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 70,
    statsBoost: { compassion: 7 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🏡",
    tags: ["كفالة", "يتيم", "أسرة"],
    motivationalQuotes: [
      "أنا وكافل اليتيم كهاتين في الجنة",
      "التزام شهري يغيّر حياة كاملة لغيرك",
      "رعايتك المستمرة تصنع أثرًا يمتد لسنوات",
    ],
  },
  {
    id: "spiritual_write_beneficial_content",
    title_ar: "كتابة محتوى نافع ينشر خيرًا",
    title_en: "Writing Beneficial Content That Spreads Good",
    description_ar: "تخصيص وقت أسبوعي لكتابة محتوى ديني أو تربوي نافع يصل لآخرين",
    description_en: "Dedicate weekly time to writing beneficial religious or educational content",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { creativity: 4, influence: 4 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "✍️",
    tags: ["كتابة", "نشر", "أثر"],
    motivationalQuotes: [
      "كلمة مكتوبة قد تصل لمن لا تصله بصوتك",
      "الأثر المكتوب يبقى بعد أن تنسى أنت كتبته",
      "من ألّف حرفًا نافعًا، شارك في نشر الخير",
    ],
  },
  {
    id: "spiritual_lead_study_circle",
    title_ar: "قيادة مجموعة ذكر أو تعلم",
    title_en: "Leading a Remembrance or Study Group",
    description_ar: "تنظيم وقيادة لقاء أسبوعي منتظم لمجموعة تجتمع على ذكر أو تعلم",
    description_en: "Organizing and leading a regular weekly gathering for remembrance or learning",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 62,
    statsBoost: { influence: 6, wisdom: 2 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🧑‍🤝‍🧑",
    tags: ["قيادة", "مجموعة", "أسبوعي"],
    motivationalQuotes: [
      "ما اجتمع قوم يذكرون الله إلا غشيتهم السكينة",
      "من جمع الناس على خير، له مثل أجرهم",
      "القيادة بالخير مسؤولية وأجر معًا",
    ],
  },
  {
    id: "spiritual_patience_with_gratitude",
    title_ar: "الصبر على الابتلاء مع الشكر",
    title_en: "Patience Through Trials, Paired with Gratitude",
    description_ar: "ممارسة يومية للتوازن بين الصبر عند الصعاب والشكر على النعم القائمة",
    description_en: "A daily practice of balancing patience during hardship with gratitude for existing blessings",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 55,
    statsBoost: { spirit: 5, wisdom: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🌾",
    tags: ["صبر", "شكر", "توازن"],
    motivationalQuotes: [
      "أمر المؤمن كله خير، إن أصابته سراء شكر، وإن أصابته ضراء صبر",
      "الصبر والشكر وجهان لعملة واحدة من الرضا",
      "من جمع بينهما، لم يعجزه شيء",
    ],
  },
  {
    id: "spiritual_consistent_good_character",
    title_ar: "الإحسان الدائم في المعاملات",
    title_en: "Consistent Excellence in Dealings with Others",
    description_ar: "الحفاظ اليومي على حسن الخلق والصدق والأمانة في كل تعامل صغير أو كبير",
    description_en: "Daily commitment to maintaining good character, honesty, and trustworthiness in all dealings",
    category: "spiritual",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { compassion: 5, discipline: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 0,
    icon: "🤝",
    tags: ["خلق", "أمانة", "معاملات"],
    motivationalQuotes: [
      "أكمل المؤمنين إيمانًا أحسنهم خلقًا",
      "الخلق الحسن يبقى أثره بعد أن تُنسى الكلمات",
      "معاملة صادقة اليوم، ثقة تُبنى لسنوات",
    ],
  },
];
