import type { HabitTemplate } from "../types";

/**
 * 40 social/relational habits, 10 per difficulty tier, covering family
 * bonds, friendships, neighborly rights, social skills (active listening,
 * conflict resolution, healthy boundaries), and community/social impact.
 *
 * Given the strong overlap between this domain and core Islamic values
 * (birr al-walidayn, silat al-rahim, neighbor rights, honesty, avoiding
 * backbiting), roughly 40-50% of habits carry a general wisdom reference
 * by meaning rather than verbatim hadith citation. Phrasing throughout
 * avoids assuming a specific family structure (marital status, children,
 * living parents) — each habit is offered as an option, not a prescription
 * that presumes the user's circumstances.
 */
export const socialHabits: HabitTemplate[] = [
  // ===== Beginner (minLevel 1, xp 10-20) =====
  {
    id: "social_daily_parents_call",
    title_ar: "التواصل مع الوالدين يوميًا",
    title_en: "Daily Contact with Parents",
    description_ar: "اتصال أو زيارة يومية قصيرة بالوالدين للاطمئنان عليهما وبرّهما",
    description_en: "A short daily call or visit to check on and honor one's parents",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 16,
    statsBoost: { compassion: 3, spirit: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "📞",
    tags: ["والدين", "بر", "يومي"],
    motivationalQuotes: [
      "بر الوالدين من أعظم ما يتقرب به العبد",
      "اتصال قصير قد يُدخل السرور على قلبين",
      "من برّ والديه في حياتهما، لم يندم بعد فراقهما",
    ],
  },
  {
    id: "social_smile_five_people",
    title_ar: "الابتسام لخمسة أشخاص يوميًا",
    title_en: "Smiling at Five People Daily",
    description_ar: "الابتسام بصدق لخمسة أشخاص تقابلهم خلال يومك",
    description_en: "Genuinely smile at five people you encounter during your day",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { compassion: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 2,
    icon: "🙂",
    tags: ["ابتسامة", "لطف", "يومي"],
    motivationalQuotes: [
      "ابتسامة حقيقية تنقل شعورًا لا تنقله الكلمات",
      "ابتسامة صغيرة، قد تُغيّر يوم شخص آخر بالكامل",
      "اللطف البسيط لا يكلف شيئًا ويعطي الكثير",
    ],
  },
  {
    id: "social_listen_without_interrupting",
    title_ar: "الاستماع دون مقاطعة",
    title_en: "Listening Without Interrupting",
    description_ar: "التدرب على الاستماع الكامل للآخرين دون مقاطعتهم أثناء حديثهم",
    description_en: "Practice fully listening to others without interrupting while they speak",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { compassion: 2, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "👂",
    tags: ["استماع", "احترام", "يومي"],
    motivationalQuotes: [
      "الاستماع الحقيقي هدية نادرة في زمن الانشغال",
      "من أنصت لغيره، أشعره بأنه مهم",
      "الإنصات الصادق أعمق أشكال الاحترام",
    ],
  },
  {
    id: "social_daily_gratitude_to_someone",
    title_ar: "شكر شخص يوميًا",
    title_en: "Thanking Someone Daily",
    description_ar: "التعبير عن الشكر الصريح لشخص ساعدك أو أثّر في يومك",
    description_en: "Explicitly thank someone who helped you or positively affected your day",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { compassion: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 3,
    icon: "🙏",
    tags: ["شكر", "امتنان", "يومي"],
    motivationalQuotes: [
      "الامتنان المعلن يقوّي كل رابط إنساني تلمسه",
      "كلمة شكر بسيطة، تقوّي رابطًا إنسانيًا",
      "الامتنان الصريح يُشعر الآخر بقيمة ما قدّمه",
    ],
  },
  {
    id: "social_avoid_backbiting_today",
    title_ar: "تجنّب الغيبة اليوم",
    title_en: "Avoiding Backbiting Today",
    description_ar: "الانتباه الواعي لتجنّب الحديث عن غياب الآخرين بما يكرهون طوال اليوم",
    description_en: "Mindfully avoid speaking about others' faults in their absence throughout the day",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 14,
    statsBoost: { discipline: 2, compassion: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 1,
    icon: "🤐",
    tags: ["غيبة", "لسان", "يومي"],
    motivationalQuotes: [
      "الغيبة ذكرك أخاك بما يكره",
      "من حفظ لسانه عن أعراض الناس، سلم قلبه",
      "الصمت عن عيوب الغائبين، خلق يزين صاحبه",
    ],
  },
  {
    id: "social_weekly_neighbor_check",
    title_ar: "التواصل مع جار أسبوعيًا",
    title_en: "Weekly Neighbor Check-In",
    // Custom: يُترك للمستخدم اختيار الجار والوقت المناسب أسبوعيًا
    description_ar: "زيارة قصيرة أو تواصل بسيط مع جار للاطمئنان عليه والتقرب منه",
    description_en: "A short visit or simple check-in with a neighbor to build connection and goodwill",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 16,
    statsBoost: { compassion: 2, influence: 1 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🏠",
    tags: ["جيرة", "تواصل", "أسبوعي"],
    motivationalQuotes: [
      "ما زال جبريل يوصيني بالجار حتى ظننت أنه سيورّثه",
      "حسن الجيرة يبدأ بخطوة بسيطة نحو جارك",
      "من عرف حق جاره، أمن شره وأمن هو منه",
    ],
  },
  {
    id: "social_check_on_friend",
    title_ar: "رسالة تفقّد لصديق",
    title_en: "A Check-In Message to a Friend",
    description_ar: "إرسال رسالة قصيرة صادقة لصديق للاطمئنان عليه دون سبب معين",
    description_en: "Send a short, genuine message to a friend to check on them without a specific reason",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { compassion: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 3,
    icon: "💬",
    tags: ["صداقة", "تواصل", "يومي"],
    motivationalQuotes: [
      "صديق يتذكرك بلا سبب، صديق حقيقي",
      "رسالة بسيطة قد تصل في أحوج لحظة",
      "الصداقة تُروى بالتواصل المستمر لا المناسبات فقط",
    ],
  },
  {
    id: "social_dua_for_parents",
    title_ar: "الدعاء للوالدين",
    title_en: "Supplicating for One's Parents",
    description_ar: "الدعاء يوميًا للوالدين بالرحمة والمغفرة والصحة",
    description_en: "Daily supplication for one's parents' mercy, forgiveness, and health",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { spirit: 2, compassion: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 2,
    icon: "🤲",
    tags: ["دعاء", "والدين", "يومي"],
    motivationalQuotes: [
      "رب ارحمهما كما ربياني صغيرًا",
      "دعاء الولد لوالديه، برّ يمتد بعد كل لحظة",
      "لحظة دعاء صادقة، وفاء لا يُقدَّر بثمن",
    ],
  },
  {
    id: "social_genuine_compliment",
    title_ar: "مجاملة صادقة يوميًا",
    title_en: "A Genuine Compliment Daily",
    description_ar: "تقديم مجاملة صادقة ومحددة لشخص تستحق جهده أو صفة فيه التقدير",
    description_en: "Offer a genuine, specific compliment to someone whose effort or trait deserves recognition",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { compassion: 2, influence: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 2,
    icon: "✨",
    tags: ["مجاملة", "تقدير", "يومي"],
    motivationalQuotes: [
      "كلمة تقدير صادقة تبقى في الذاكرة أطول مما نتوقع",
      "تقدير صادق يمنح الآخر دفعة لا يتوقعها",
      "من أثنى بحق، لم يُطرِ بل أنصف",
    ],
  },
  {
    id: "social_small_daily_help",
    title_ar: "مساعدة شخص بعمل بسيط يوميًا",
    title_en: "Helping Someone with a Small Deed Daily",
    description_ar: "تقديم مساعدة صغيرة وملموسة لشخص يحتاجها كل يوم",
    description_en: "Offer a small, tangible act of help to someone who needs it each day",
    category: "social",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { compassion: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🤝",
    tags: ["مساعدة", "عطاء", "يومي"],
    motivationalQuotes: [
      "خير الناس أنفعهم للناس",
      "مساعدة صغيرة يوميًا، عادة تصنع أثرًا كبيرًا مع الوقت",
      "من يسّر على غيره، يسّر الله عليه",
    ],
  },

  // ===== Intermediate (minLevel 15, xp 20-35) =====
  {
    id: "social_weekly_family_dinner",
    title_ar: "عشاء عائلي أسبوعي",
    title_en: "Weekly Family Dinner",
    // Custom: يُترك للمستخدم تحديد اليوم المناسب لجدول أسرته
    description_ar: "تخصيص عشاء أسبوعي ثابت يجتمع فيه أفراد الأسرة بلا شاشات أو انشغال",
    description_en: "Dedicate a fixed weekly dinner where family members gather without screens or distractions",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { compassion: 3, spirit: 1 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 60,
    icon: "🍲",
    tags: ["أسرة", "عشاء", "أسبوعي"],
    motivationalQuotes: [
      "مائدة أسبوعية ثابتة، رابط عائلي لا يُستهان به",
      "الوقت المشترك حول الطعام يقوّي الأسرة أكثر من كثير من الكلام",
      "من حافظ على لقاء أسرته، حصّن أبناءه من الغربة الداخلية",
    ],
  },
  {
    id: "social_weekly_friend_meetup",
    title_ar: "لقاء صديق أسبوعيًا",
    title_en: "Weekly Friend Meetup",
    // Custom: يُترك للمستخدم اختيار الصديق والوقت المناسب أسبوعيًا
    description_ar: "لقاء أسبوعي منتظم مع صديق للحفاظ على صداقة حقيقية ومستمرة",
    description_en: "A regular weekly meetup with a friend to maintain a genuine, lasting friendship",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "☕",
    tags: ["صداقة", "لقاء", "أسبوعي"],
    motivationalQuotes: [
      "الصداقة الحقيقية تحتاج وقتًا حقيقيًا لتُحافَظ عليها",
      "صديق تلتقيه بانتظام، صديق لا يبتعد بصمت",
      "لقاء أسبوعي بسيط، يمنع الصداقات من الذبول",
    ],
  },
  {
    id: "social_monthly_relative_visit",
    title_ar: "زيارة قريب شهريًا",
    title_en: "Monthly Relative Visit",
    // Custom: يُترك للمستخدم اختيار القريب المناسب كل شهر
    description_ar: "زيارة شهرية لأحد الأقارب الذين قد يقل التواصل معهم لصلة الرحم",
    description_en: "A monthly visit to a relative you don't often connect with, to maintain family ties",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { compassion: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "👨‍👩‍👧",
    tags: ["صلة رحم", "أقارب", "شهري"],
    motivationalQuotes: [
      "من وصل رحمه، وصله الله",
      "زيارة شهرية بسيطة، تُبقي الرحم متصلة لا مقطوعة",
      "لا تنسَ من قد ينساه غيرك",
    ],
  },
  {
    id: "social_active_listening_practice",
    title_ar: "ممارسة الاستماع الفعّال",
    title_en: "Active Listening Practice",
    description_ar: "التدرب على الاستماع الفعّال: إعادة صياغة ما قاله الآخر للتأكد من الفهم",
    description_en: "Practice active listening: paraphrasing what the other person said to confirm understanding",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { wisdom: 3, compassion: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🗨️",
    tags: ["استماع فعّال", "مهارة", "يومي"],
    motivationalQuotes: [
      "الاستماع الفعّال يجعل المتحدث يشعر بأنه مسموع حقًا",
      "من أعاد صياغة كلام غيره، أثبت أنه فهمه لا سمعه فقط",
      "مهارة الإنصات تُبنى بالممارسة الواعية",
    ],
  },
  {
    id: "social_conflict_resolution_skill",
    title_ar: "تعلم مهارة حل النزاعات",
    title_en: "Learning Conflict Resolution Skills",
    description_ar: "دراسة وتطبيق أسلوب هادئ ومنصف للتعامل مع الخلافات عند حدوثها",
    description_en: "Study and apply a calm, fair approach to handling disagreements when they arise",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { wisdom: 4 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🕊️",
    tags: ["حل نزاعات", "حكمة", "يومي"],
    motivationalQuotes: [
      "الصلح خير",
      "من حلّ خلافه بحكمة، حفظ العلاقة أكثر مما حفظ رأيه",
      "الهدوء في النزاع، نصف الحل",
    ],
  },
  {
    id: "social_written_thank_you",
    title_ar: "كتابة رسالة شكر",
    title_en: "Writing a Thank-You Note",
    // Custom: يُترك للمستخدم اختيار الشخص والمناسبة المناسبة أسبوعيًا
    description_ar: "كتابة رسالة شكر مفصّلة لشخص أثّر إيجابيًا في حياتك",
    description_en: "Write a detailed thank-you note to someone who has positively impacted your life",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "✉️",
    tags: ["شكر", "كتابة", "أسبوعي"],
    motivationalQuotes: [
      "الشكر المكتوب يبقى أثره أطول من الكلمة العابرة",
      "رسالة صادقة قد تُحفَظ لسنوات",
      "امتنان مفصّل يُشعر الآخر بقيمة حقيقية لا عابرة",
    ],
  },
  {
    id: "social_relatives_news_followup",
    title_ar: "متابعة أخبار الأقارب",
    title_en: "Following Up on Relatives' News",
    // Custom: يُترك للمستخدم تحديد يوم أسبوعي ثابت للمتابعة
    description_ar: "تخصيص وقت أسبوعي للاطمئنان على أخبار الأقارب الذين لا تلتقيهم كثيرًا",
    description_en: "Dedicate weekly time to check on relatives you don't often see",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "📱",
    tags: ["صلة رحم", "متابعة", "أسبوعي"],
    motivationalQuotes: [
      "صلة الرحم لا تحتاج مناسبة، تحتاج فقط أن تتذكر",
      "من تفقّد أقاربه، حفظ رابطًا قد يضعف بالإهمال",
      "الاطمئنان البسيط، صلة رحم في أبسط صورها",
    ],
  },
  {
    id: "social_daily_quality_time_children",
    title_ar: "وقت جودة يومي مع الأبناء",
    title_en: "Daily Quality Time with Children",
    description_ar: "تخصيص وقت يومي خالص للانتباه الكامل لمن تربيهم من الأبناء، بلا هاتف أو انشغال",
    description_en: "Dedicate daily undivided attention to the children you're raising, free from phones or distractions",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { compassion: 4 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 20,
    icon: "👨‍👧‍👦",
    tags: ["أبناء", "تربية", "يومي"],
    motivationalQuotes: [
      "كلكم راعٍ وكلكم مسؤول عن رعيته",
      "وقت الجودة أهم من كثرة الوقت بلا انتباه",
      "الطفل يتذكر الحضور الحقيقي أكثر مما يتذكر الهدايا",
    ],
  },
  {
    id: "social_sincere_apology",
    title_ar: "الاعتذار الصادق عند الخطأ",
    title_en: "A Sincere Apology When Wrong",
    description_ar: "الاعتراف الصريح بالخطأ والاعتذار الصادق دون تبرير مفرط عند الإساءة لأحد",
    description_en: "Openly acknowledge mistakes and sincerely apologize without excessive justification when you've wronged someone",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { wisdom: 2, compassion: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🙇",
    tags: ["اعتذار", "صدق", "يومي"],
    motivationalQuotes: [
      "الاعتذار الصادق قوة لا ضعف",
      "من اعترف بخطئه بسرعة، حفظ علاقته من التصدع",
      "كلمة آسف صادقة، تُصلح ما تُفسده الأنفة",
    ],
  },
  {
    id: "social_monthly_social_gathering",
    title_ar: "المشاركة في مناسبة اجتماعية شهريًا",
    title_en: "Participating in a Monthly Social Gathering",
    // Custom: يُترك للمستخدم اختيار المناسبة المناسبة كل شهر
    description_ar: "حضور مناسبة اجتماعية شهرية تقوّي روابطك مع دائرتك الاجتماعية",
    description_en: "Attend a monthly social gathering that strengthens your ties with your social circle",
    category: "social",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 20,
    statsBoost: { compassion: 2, influence: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🎉",
    tags: ["مناسبات", "دائرة اجتماعية", "شهري"],
    motivationalQuotes: [
      "الحضور المنتظم في حياة الآخرين، رابط لا يُستبدل بالرسائل",
      "مناسبة واحدة شهريًا، تبقي دائرتك الاجتماعية حية",
      "من حضر لأصدقائه في المناسبات، حضروا له وقت الحاجة",
    ],
  },

  // ===== Advanced (minLevel 35, xp 35-50) =====
  {
    id: "social_deep_conversations_parents",
    title_ar: "محادثات عميقة أسبوعية مع الوالدين",
    title_en: "Weekly Deep Conversations with Parents",
    // Custom: يُترك للمستخدم تحديد الوقت المناسب أسبوعيًا
    description_ar: "تخصيص وقت أسبوعي لمحادثة عميقة وصادقة مع الوالدين، أبعد من الأسئلة الروتينية",
    description_en: "Dedicate weekly time for a deep, genuine conversation with parents, beyond routine questions",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { compassion: 4, wisdom: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "💛",
    tags: ["والدين", "محادثة عميقة", "أسبوعي"],
    motivationalQuotes: [
      "رضا الله في رضا الوالدين",
      "محادثة عميقة واحدة، تعرّفك على والديك أكثر من سنوات من الأسئلة السطحية",
      "الوقت مع الوالدين كنز لا يعرف قيمته إلا من فقده",
    ],
  },
  {
    id: "social_weekly_mentoring_person",
    title_ar: "توجيه شخص أسبوعيًا",
    title_en: "Weekly Mentoring of a Person",
    // Custom: يُترك للمستخدم اختيار الشخص والوقت المناسب أسبوعيًا
    description_ar: "تخصيص وقت أسبوعي لتوجيه ودعم شخص يحتاج نصيحة أو خبرتك",
    description_en: "Dedicate weekly time to guide and support someone who needs advice or your expertise",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { influence: 4, compassion: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🧭",
    tags: ["توجيه", "دعم", "أسبوعي"],
    motivationalQuotes: [
      "من استثمر وقته في توجيه غيره، رأى أثره يمتد بعيدًا",
      "توجيه صادق أسبوعي، قد يغيّر مسار حياة شخص",
      "من استثمر وقته في غيره، ضاعف أثره في العالم",
    ],
  },
  {
    id: "social_regular_community_involvement",
    title_ar: "المشاركة المجتمعية المنتظمة",
    title_en: "Regular Community Involvement",
    // Custom: يُترك للمستخدم اختيار نوع المشاركة المناسبة
    description_ar: "المشاركة المنتظمة في نشاط أو مبادرة تخدم المجتمع المحلي",
    description_en: "Regular participation in an activity or initiative that serves the local community",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { influence: 3, compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🏘️",
    tags: ["مجتمع", "مشاركة", "منتظم"],
    motivationalQuotes: [
      "الانتماء الحقيقي يُبنى بالمشاركة الفعلية لا بالحضور الشكلي",
      "المشاركة المجتمعية المنتظمة تبني انتماءً حقيقيًا",
      "من ساهم في مجتمعه، شعر بأنه جزء منه لا متفرج عليه",
    ],
  },
  {
    id: "social_monthly_volunteer_work",
    title_ar: "عمل تطوعي شهري",
    title_en: "Monthly Volunteer Work",
    // Custom: يُترك للمستخدم اختيار جهة التطوع المناسبة كل شهر
    description_ar: "تخصيص وقت شهري للعمل التطوعي في قضية أو جهة تؤمن بها",
    description_en: "Dedicate monthly time to volunteer work for a cause or organization you believe in",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { compassion: 5 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 120,
    icon: "🤲",
    tags: ["تطوع", "عمل خيري", "شهري"],
    motivationalQuotes: [
      "خير الناس أنفعهم للناس",
      "التطوع المنتظم يحوّل النية الطيبة إلى أثر ملموس",
      "من أعطى وقته لغيره، ربح ما لا يُشترى بالمال",
    ],
  },
  {
    id: "social_build_family_traditions",
    title_ar: "بناء تقاليد عائلية",
    title_en: "Building Family Traditions",
    // Custom: يُترك للمستخدم تحديد طبيعة التقاليد المناسبة لأسرته
    description_ar: "إنشاء والمحافظة على تقاليد عائلية بسيطة تُقوّي روابط الأسرة عبر الزمن",
    description_en: "Create and maintain simple family traditions that strengthen bonds over time",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { compassion: 3, creativity: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🕯️",
    tags: ["تقاليد عائلية", "ذكريات", "أسرة"],
    motivationalQuotes: [
      "التقاليد العائلية ذاكرة مشتركة تربط الأجيال",
      "طقس بسيط متكرر، يصبح ذكرى تدوم عمرًا",
      "من بنى تقاليد لأسرته، ترك لها هوية تنتمي إليها",
    ],
  },
  {
    id: "social_regular_family_council",
    title_ar: "مجلس عائلي منتظم",
    title_en: "Regular Family Council",
    // Custom: يُترك للمستخدم تحديد وتيرة المجلس المناسبة لأسرته
    description_ar: "اجتماع عائلي منتظم لمناقشة القرارات والمشاعر بصراحة واحترام متبادل",
    description_en: "A regular family meeting to openly discuss decisions and feelings with mutual respect",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { wisdom: 3, compassion: 3 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 45,
    icon: "🗣️",
    tags: ["مجلس عائلي", "تواصل", "منتظم"],
    motivationalQuotes: [
      "الشورى في الأسرة تبني ثقة لا تُبنى بالأوامر وحدها",
      "من أشرك أسرته في القرار، أشركهم في الشعور بالانتماء",
      "الحوار المنتظم يمنع تراكم الخلافات الصغيرة",
    ],
  },
  {
    id: "social_calm_conflict_handling",
    title_ar: "التعامل الهادئ مع النزاعات",
    title_en: "Calm Handling of Conflicts",
    description_ar: "تطبيق واعٍ للهدوء وضبط النفس عند مواجهة خلاف بدلاً من ردة الفعل الفورية",
    description_en: "Mindfully apply calm and self-control when facing a disagreement instead of reacting instantly",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { discipline: 3, wisdom: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🧘‍♂️",
    tags: ["نزاعات", "ضبط النفس", "يومي"],
    motivationalQuotes: [
      "ليس الشديد بالصرعة، إنما الشديد من يملك نفسه عند الغضب",
      "الهدوء في لحظة الخلاف، قوة لا يملكها الجميع",
      "من ضبط غضبه، حفظ علاقات كثيرة من الانهيار",
    ],
  },
  {
    id: "social_healthy_boundaries",
    title_ar: "وضع حدود صحية بلطف",
    title_en: "Setting Healthy Boundaries with Kindness",
    description_ar: "التعبير الواضح واللطيف عن حدودك الشخصية دون شعور بالذنب أو قسوة غير ضرورية",
    description_en: "Clearly and kindly express your personal boundaries without guilt or unnecessary harshness",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { wisdom: 3, discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 5,
    icon: "🛡️",
    tags: ["حدود", "احترام الذات", "يومي"],
    motivationalQuotes: [
      "من احترم حدوده، علّم الآخرين كيف يحترمونها أيضًا",
      "من وضع حدوده بلطف، حمى علاقاته من الاستنزاف",
      "قول لا بأدب، مهارة تحتاج شجاعة هادئة",
    ],
  },
  {
    id: "social_support_friend_in_need",
    title_ar: "دعم صديق يمر بضائقة",
    title_en: "Supporting a Friend Going Through Hardship",
    // Custom: يُترك للمستخدم تحديد الشخص والدعم المناسب حسب الحاجة
    description_ar: "تخصيص وقت واهتمام حقيقي لدعم صديق يمر بظرف صعب في حياته",
    description_en: "Dedicate genuine time and attention to support a friend going through a difficult time",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { compassion: 5 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🫂",
    tags: ["دعم", "صداقة", "مساندة"],
    motivationalQuotes: [
      "من فرّج عن مسلم كربة، فرّج الله عنه كربة",
      "الحضور في الضيق يُعرَف به الصديق الحقيقي",
      "من ساند غيره وقت الحاجة، بنى ثقة لا تُشترى",
    ],
  },
  {
    id: "social_far_relatives_effort",
    title_ar: "صلة الرحم البعيدة بجهد فعلي",
    title_en: "Actively Maintaining Distant Family Ties",
    // Custom: يُترك للمستخدم تحديد وتيرة التواصل مع كل الأقارب لا الأقرب فقط
    description_ar: "بذل جهد واعٍ للتواصل مع كل الأقارب، لا الأقرب منهم فقط، حفاظًا على الرحم كاملة",
    description_en: "Make a conscious effort to connect with all relatives, not just the closest, to maintain the whole family circle",
    category: "social",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { compassion: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🌳",
    tags: ["صلة رحم", "أقارب", "شامل"],
    motivationalQuotes: [
      "ليس الواصل بالمكافئ، ولكن الواصل الذي إذا قُطعت رحمه وصلها",
      "من وصل حتى من قطعه، بلغ أعلى درجات البر",
      "الرحم الشاملة لا تفرّق بين قريب وبعيد",
    ],
  },

  // ===== Expert (minLevel 60, xp 50-80) =====
  {
    id: "social_build_supportive_community",
    title_ar: "بناء مجتمع داعم",
    title_en: "Building a Supportive Community",
    // Custom: يُترك للمستخدم تحديد طبيعة المجتمع ووتيرة الأنشطة
    description_ar: "إنشاء ورعاية مساحة يشعر فيها الأعضاء بالدعم والانتماء الحقيقي",
    description_en: "Create and nurture a space where members feel genuine support and belonging",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 68,
    statsBoost: { influence: 5, compassion: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🌐",
    tags: ["مجتمع داعم", "انتماء", "خبير"],
    motivationalQuotes: [
      "المؤمن للمؤمن كالبنيان يشد بعضه بعضًا",
      "مجتمع داعم واحد، يحمل كثيرين حين يضعفون",
      "من بنى مساحة أمان لغيره، بنى أثرًا يفوق عمره",
    ],
  },
  {
    id: "social_lead_social_initiatives",
    title_ar: "قيادة مبادرات اجتماعية",
    title_en: "Leading Social Initiatives",
    // Custom: يُترك للمستخدم تحديد طبيعة المبادرة ووتيرة العمل عليها
    description_ar: "قيادة مبادرة اجتماعية تخدم قضية حقيقية وتحشد آخرين للمشاركة فيها",
    description_en: "Lead a social initiative that serves a real cause and mobilizes others to participate",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 65,
    statsBoost: { influence: 6, compassion: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "📣",
    tags: ["قيادة", "مبادرات", "أثر"],
    motivationalQuotes: [
      "القيادة الاجتماعية الحقيقية تبدأ بشخص واحد يرفض الاكتفاء بالمشاهدة",
      "القيادة الاجتماعية الحقيقية تُقاس بمن تُحرّكهم للخير",
      "مبادرة واحدة قادها فرد، قد تُغيّر واقع مجتمع كامل",
    ],
  },
  {
    id: "social_multi_generational_bonds",
    title_ar: "روابط بين الأجيال",
    title_en: "Building Multi-Generational Bonds",
    // Custom: يُترك للمستخدم تحديد الوتيرة المناسبة للتواصل بين الأجيال
    description_ar: "بناء جسور تواصل حقيقية بين الأجيال المختلفة في العائلة أو المجتمع",
    description_en: "Build genuine connection bridges between different generations in family or community",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { compassion: 4, wisdom: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "👴",
    tags: ["أجيال", "حكمة", "روابط"],
    motivationalQuotes: [
      "من وقّر كبيره واحترم صغيره، وصل حكمة إلى قلوب مختلفة",
      "الحوار بين الأجيال يحفظ الحكمة القديمة والحيوية الجديدة معًا",
      "من ربط الأجيال ببعضها، منع الفجوة أن تتسع",
    ],
  },
  {
    id: "social_writing_about_relationships",
    title_ar: "الكتابة عن العلاقات ومشاركة الخبرة",
    title_en: "Writing About Relationships and Sharing Experience",
    // Custom: يُترك للمستخدم تحديد الوسيلة والوتيرة المناسبة للنشر
    description_ar: "توثيق ومشاركة خبرتك في بناء علاقات صحية لتفيد آخرين يمرون بتجارب مشابهة",
    description_en: "Document and share your experience building healthy relationships to help others facing similar situations",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 55,
    statsBoost: { creativity: 3, wisdom: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "📝",
    tags: ["كتابة", "علاقات", "مشاركة"],
    motivationalQuotes: [
      "خبرة صادقة موثّقة، قد تنقذ علاقة شخص لا تعرفه",
      "من شارك حكمته في العلاقات، وسّع دائرة نفعه",
      "الكلمة الصادقة عن التجربة، أصدق من النصيحة النظرية",
    ],
  },
  {
    id: "social_wide_impact_initiative",
    title_ar: "مبادرات ذات أثر واسع",
    title_en: "Wide-Impact Initiatives",
    // Custom: يُترك للمستخدم تحديد نطاق ووتيرة العمل على المبادرة
    description_ar: "العمل المنتظم على مبادرة تتجاوز الدائرة القريبة لتصل لعدد أكبر من المستفيدين",
    description_en: "Regular work on an initiative that extends beyond your immediate circle to reach a wider group of beneficiaries",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 70,
    statsBoost: { influence: 6, compassion: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🌍",
    tags: ["أثر واسع", "مبادرة", "خبير"],
    motivationalQuotes: [
      "الأثر الحقيقي لا يُقاس بحجم البداية، بل باستمرارها",
      "الأثر الواسع يبدأ دائمًا بخطوة محلية صادقة",
      "من فكّر أبعد من دائرته، خدم من لن يعرفهم أبدًا",
    ],
  },
  {
    id: "social_legacy_project",
    title_ar: "مشاريع الإرث المستمر",
    title_en: "Legacy Projects",
    // Custom: يُترك للمستخدم تحديد طبيعة المشروع طويل المدى ووتيرة العمل عليه
    description_ar: "العمل على مشروع يستمر نفعه بعد انقطاعك عنه، كصدقة جارية اجتماعية أو معرفية",
    description_en: "Work on a project whose benefit continues after you, like an ongoing social or knowledge-based charity",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 72,
    statsBoost: { wisdom: 5, compassion: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🌳",
    tags: ["إرث", "صدقة جارية", "خبير"],
    motivationalQuotes: [
      "إذا مات ابن آدم انقطع عمله إلا من صدقة جارية أو علم ينتفع به",
      "من بنى مشروعًا يستمر بعده، لم يمت أثره بموته",
      "الإرث الحقيقي ليس ما تملكه، بل ما يبقى نفعه بعدك",
    ],
  },
  {
    id: "social_mediate_others_conflicts",
    title_ar: "الوساطة في حل نزاعات الآخرين",
    title_en: "Mediating Others' Conflicts",
    // Custom: يُترك للمستخدم تحديد وتيرة الوساطة حسب الحاجة الفعلية
    description_ar: "استخدام حكمتك ومهارتك لمساعدة طرفين متنازعين على الوصول لحل عادل",
    description_en: "Use your wisdom and skill to help two conflicting parties reach a fair resolution",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 62,
    statsBoost: { wisdom: 6 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "⚖️",
    tags: ["وساطة", "إصلاح", "حكمة"],
    motivationalQuotes: [
      "ألا أخبركم بأفضل من درجة الصيام والصلاة والصدقة؟ إصلاح ذات البين",
      "من أصلح بين اثنين، منع شرًا وبنى خيرًا معًا",
      "الوساطة العادلة تحتاج حكمة أكثر مما تحتاج سلطة",
    ],
  },
  {
    id: "social_deep_relationship_network",
    title_ar: "رعاية شبكة علاقات واسعة بعمق",
    title_en: "Nurturing a Wide Network of Relationships with Depth",
    // Custom: يُترك للمستخدم تحديد وتيرة رعاية الشبكة بما يناسب حياته
    description_ar: "المحافظة على شبكة علاقات واسعة دون أن تفقد عمق كل علاقة فيها",
    description_en: "Maintain a wide network of relationships without losing the depth of each individual connection",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 56,
    statsBoost: { compassion: 4, influence: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🕸️",
    tags: ["شبكة علاقات", "عمق", "خبير"],
    motivationalQuotes: [
      "العلاقات الكثيرة بلا عمق، أضعف من قليل صادق",
      "من وسّع شبكته دون أن يفقد صدقه، امتلك ثروة نادرة",
      "الاتساع والعمق معًا، مهارة تحتاج وعيًا مستمرًا بالوقت",
    ],
  },
  {
    id: "social_values_based_parenting",
    title_ar: "تربية قائمة على القيم",
    title_en: "Values-Based Parenting",
    description_ar: "توجيه من تربّيهم بالقدوة والقيم الراسخة أكثر من الأوامر والتوجيه اللفظي فقط",
    description_en: "Guide those you're raising through example and grounded values more than commands and verbal instruction alone",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { wisdom: 5, compassion: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🌱",
    tags: ["تربية", "قيم", "قدوة"],
    motivationalQuotes: [
      "القيم التي تُعاش أمام الأبناء، تترسخ أكثر من أي نصيحة مباشرة",
      "القدوة العملية تعلّم ما لا تعلّمه ألف كلمة",
      "من ربّى بالقيم لا بالخوف، بنى جيلاً واثقًا بذاته",
    ],
  },
  {
    id: "social_continuous_social_example",
    title_ar: "القدوة الاجتماعية المستمرة",
    title_en: "Being a Continuous Social Example",
    description_ar: "المحافظة اليومية على أن تكون قدوة حقيقية في الصدق والوفاء وحسن المعاملة",
    description_en: "Daily maintain being a genuine example of honesty, loyalty, and good treatment of others",
    category: "social",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { compassion: 5, wisdom: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 10,
    icon: "🌟",
    tags: ["قدوة", "خلق", "يومي"],
    motivationalQuotes: [
      "أكمل المؤمنين إيمانًا أحسنهم خلقًا",
      "القدوة المستمرة أقوى من ألف موعظة",
      "من عاش قيمه أمام الناس، أثّر فيهم دون أن يتكلم",
    ],
  },
];
