import type { HabitTemplate } from "../types";

/**
 * 40 professional/work habits, 10 per difficulty tier, covering time
 * management, deep work, planning, skill growth, networking, automation,
 * leadership, and entrepreneurship.
 */
export const workHabits: HabitTemplate[] = [
  // ===== Beginner (minLevel 1, xp 10-20) =====
  {
    id: "work_clean_desk_5min",
    title_ar: "ترتيب المكتب 5 دقائق",
    title_en: "5-Minute Desk Tidy-Up",
    description_ar: "تخصيص خمس دقائق كل صباح لترتيب مساحة العمل قبل البدء",
    description_en: "Spend five minutes each morning tidying your workspace before starting",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 2 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 5,
    icon: "🧹",
    tags: ["ترتيب", "بداية اليوم", "يومي"],
    motivationalQuotes: [
      "مساحة مرتبة، ذهن أكثر تركيزًا",
      "خمس دقائق فقط تفصلك عن يوم أكثر وضوحًا",
      "البداية المنظمة تصنع فرقًا طوال اليوم",
    ],
  },
  {
    id: "work_three_priorities",
    title_ar: "كتابة 3 أولويات اليوم",
    title_en: "Write 3 Priorities for the Day",
    description_ar: "تحديد ثلاث مهام أساسية فقط يجب إنجازها اليوم قبل أي شيء آخر",
    description_en: "Identify only three essential tasks that must get done today",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 15,
    statsBoost: { discipline: 3, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 5,
    icon: "📋",
    tags: ["أولويات", "تخطيط", "يومي"],
    motivationalQuotes: [
      "ثلاث أولويات واضحة، خير من عشر مهام مشتتة",
      "من عرف أولوياته، أنجز رغم الزحام",
      "التركيز يبدأ بالاختيار، لا بالفعل",
    ],
  },
  {
    id: "work_no_phone_first_hour",
    title_ar: "عدم فتح الهاتف أول ساعة عمل",
    title_en: "No Phone in the First Work Hour",
    description_ar: "تجنّب فتح الهاتف والتطبيقات المشتتة خلال أول ساعة من العمل",
    description_en: "Avoid opening your phone or distracting apps during the first work hour",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 15,
    statsBoost: { discipline: 3 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 60,
    icon: "📵",
    tags: ["تركيز", "انضباط", "يومي"],
    motivationalQuotes: [
      "أول ساعة تحدد نمط بقية يومك",
      "من ملك أول ساعته، ملك زمام يومه",
      "التركيز المبكر يوفر وقتًا أطول لاحقًا",
    ],
  },
  {
    id: "work_inbox_clear",
    title_ar: "تفريغ صندوق البريد الوارد",
    title_en: "Clear the Inbox",
    description_ar: "الرد على الرسائل المهمة وأرشفة الباقي حتى لا يتراكم صندوق الوارد",
    description_en: "Respond to important emails and archive the rest to avoid inbox pile-up",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "📧",
    tags: ["بريد", "تنظيم", "يومي"],
    motivationalQuotes: [
      "صندوق فارغ، ذهن أخف",
      "التراكم اليوم يعني فوضى الغد",
      "دقائق قليلة يوميًا توفر ساعات لاحقًا",
    ],
  },
  {
    id: "work_tomorrow_todo",
    title_ar: "ترتيب قائمة مهام الغد",
    title_en: "Prepare Tomorrow's To-Do List",
    description_ar: "تخصيص وقت في نهاية اليوم لكتابة خطة اليوم التالي قبل مغادرة العمل",
    description_en: "Spend time at day's end writing tomorrow's plan before leaving work",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { discipline: 2, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "🗒️",
    tags: ["تخطيط", "مساء", "يومي"],
    motivationalQuotes: [
      "من خطط لغده الليلة، بدأ يومه بثقة",
      "الغد الواضح يبدأ من الليلة السابقة",
      "خطة جاهزة تعني بداية بلا تردد",
    ],
  },
  {
    id: "work_hourly_break",
    title_ar: "استراحة قصيرة كل ساعة",
    title_en: "Short Break Every Hour",
    description_ar: "الوقوف والتمدد لدقيقتين كل ساعة عمل للحفاظ على النشاط الذهني",
    description_en: "Stand and stretch for two minutes every work hour to maintain mental sharpness",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 1, wisdom: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 2,
    icon: "🧍",
    tags: ["استراحة", "صحة", "يومي"],
    motivationalQuotes: [
      "استراحة قصيرة تمنع الإرهاق الطويل",
      "الجسم المتحرك يخدم الذهن المركّز",
      "دقيقتان كل ساعة، ثمن بسيط لطاقة متجددة",
    ],
  },
  {
    id: "work_one_win_before_sleep",
    title_ar: "تدوين إنجاز واحد قبل النوم",
    title_en: "Note One Win Before Sleep",
    description_ar: "كتابة إنجاز واحد تحقق اليوم، مهما كان صغيرًا، قبل الخلود للنوم",
    description_en: "Write down one accomplishment from today, however small, before sleeping",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { wisdom: 2 },
    frequency: "daily",
    suggestedTime: "night",
    estimatedMinutes: 5,
    icon: "✅",
    tags: ["إنجاز", "تأمل", "يومي"],
    motivationalQuotes: [
      "خير الأعمال أدومها وإن قل",
      "إنجاز صغير موثّق، أفضل من يوم منسي",
      "التقدير الذاتي وقود للاستمرار",
    ],
  },
  {
    id: "work_arrive_early",
    title_ar: "الوصول قبل الموعد بعشر دقائق",
    title_en: "Arrive Ten Minutes Early",
    description_ar: "الوصول للعمل أو بدء المهمة قبل الموعد المحدد بعشر دقائق دون استعجال",
    description_en: "Arrive at work or start a task ten minutes before the scheduled time, unrushed",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 2 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 10,
    icon: "⏰",
    tags: ["انضباط", "التزام", "يومي"],
    motivationalQuotes: [
      "من بكّر إلى عمله، بكّرت إليه الفرص",
      "الوقت الفائض يمنحك هدوءًا لا يشتريه المال",
      "الالتزام الصغير يبني سمعة كبيرة",
    ],
  },
  {
    id: "work_notifications_off",
    title_ar: "إغلاق الإشعارات أثناء العمل",
    title_en: "Turn Off Notifications While Working",
    description_ar: "تعطيل إشعارات الهاتف والحاسوب خلال فترات العمل المركّز",
    description_en: "Disable phone and computer notifications during focused work periods",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 12,
    statsBoost: { discipline: 2 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 1,
    icon: "🔕",
    tags: ["تركيز", "إشعارات", "يومي"],
    motivationalQuotes: [
      "الصمت الرقمي يفتح مساحة للتركيز العميق",
      "كل إشعار مقاطع، هو دقائق مسروقة من إنجازك",
      "اختر متى تنتبه، لا تدع التطبيقات تختار لك",
    ],
  },
  {
    id: "work_hydration_reminder",
    title_ar: "شرب الماء بانتظام أثناء العمل",
    title_en: "Stay Hydrated While Working",
    description_ar: "تذكّر شرب كوب ماء كل ساعتين للحفاظ على التركيز والنشاط",
    description_en: "Remember to drink a glass of water every two hours to stay focused and energized",
    category: "work",
    difficulty: "beginner",
    minLevel: 1,
    xpReward: 10,
    statsBoost: { discipline: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 1,
    icon: "💧",
    tags: ["صحة", "تركيز", "يومي"],
    motivationalQuotes: [
      "ذهن رطب، تركيز أوضح",
      "عادة صغيرة تحمي طاقتك طوال اليوم",
      "الجسم المُهمَل لا يخدم عملاً متقنًا",
    ],
  },

  // ===== Intermediate (minLevel 15, xp 20-35) =====
  {
    id: "work_pomodoro_technique",
    title_ar: "تقنية بومودورو للتركيز",
    title_en: "Pomodoro Focus Technique",
    description_ar: "العمل في فترات مركّزة مدتها 25 دقيقة مع استراحات قصيرة بينها",
    description_en: "Work in focused 25-minute intervals with short breaks in between",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 25,
    statsBoost: { discipline: 3, intelligence: 1 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 25,
    icon: "🍅",
    tags: ["بومودورو", "تركيز", "إنتاجية"],
    motivationalQuotes: [
      "خمس وعشرون دقيقة من التركيز الكامل، تعادل ساعة من التشتت",
      "العمل المجزّأ بذكاء، أقوى من العمل المستمر بلا خطة",
      "استراحة قصيرة بعد كل جولة، تجدد طاقتك للجولة التالية",
    ],
  },
  {
    id: "work_daily_deep_work_hour",
    title_ar: "ساعة عمل عميق يوميًا",
    title_en: "One Hour of Daily Deep Work",
    description_ar: "تخصيص ساعة كاملة يوميًا لمهمة واحدة تتطلب تركيزًا عاليًا بلا مقاطعة",
    description_en: "Dedicate a full hour daily to one task requiring high focus without interruption",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 30,
    statsBoost: { discipline: 4, intelligence: 2 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 60,
    icon: "🎯",
    tags: ["عمل عميق", "تركيز", "يومي"],
    motivationalQuotes: [
      "ساعة عمل عميق تنجز ما لا تنجزه أربع ساعات مشتتة",
      "العمل العميق مهارة تُصقل بالممارسة اليومية",
      "من حجز وقته للتركيز، حجز مكانه بين المتميزين",
    ],
  },
  {
    id: "work_weekly_goals_review",
    title_ar: "مراجعة أسبوعية للأهداف",
    title_en: "Weekly Goals Review",
    // Custom: يُترك للمستخدم تحديد يوم ثابت أسبوعيًا يناسب جدوله
    description_ar: "جلسة أسبوعية لمراجعة التقدم في الأهداف وتعديل الخطة عند الحاجة",
    description_en: "A weekly session to review progress on goals and adjust the plan as needed",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 28,
    statsBoost: { wisdom: 3, discipline: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 30,
    icon: "📊",
    tags: ["مراجعة", "أهداف", "أسبوعي"],
    motivationalQuotes: [
      "من راجع خطته أسبوعيًا، صحّح مساره قبل أن يبتعد",
      "التقدم الحقيقي يحتاج توقفًا دوريًا للتأمل",
      "المراجعة ليست تراجعًا، بل خطوة للأمام بوعي",
    ],
  },
  {
    id: "work_learn_new_shortcut",
    title_ar: "تعلم اختصار أو أداة جديدة",
    title_en: "Learn a New Shortcut or Tool",
    description_ar: "تعلم اختصار لوحة مفاتيح أو أداة صغيرة تسرّع عملك أسبوعيًا",
    description_en: "Learn a keyboard shortcut or small tool weekly that speeds up your work",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { intelligence: 3 },
    frequency: "weekly",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "⌨️",
    tags: ["مهارات", "أدوات", "أسبوعي"],
    motivationalQuotes: [
      "اختصار صغير اليوم، وقت موفّر كل يوم بعده",
      "التعلم المستمر يجعل أدواتك تخدمك لا تعيقك",
      "من حسّن أدواته، حسّن نتيجة عمله",
    ],
  },
  {
    id: "work_daily_professional_reading",
    title_ar: "قراءة مقال مهني يوميًا",
    title_en: "Read a Professional Article Daily",
    description_ar: "قراءة مقال أو محتوى قصير يطوّر معرفتك في مجال عملك",
    description_en: "Read a short article or piece of content that develops your professional knowledge",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 20,
    statsBoost: { intelligence: 3 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 15,
    icon: "📰",
    tags: ["قراءة", "تطوير", "يومي"],
    motivationalQuotes: [
      "مقال واحد يوميًا يبني معرفة عام كامل",
      "من واظب على التعلم، لم يتجاوزه الزمن",
      "المعرفة المتجددة سلاح لا يصدأ",
    ],
  },
  {
    id: "work_plan_before_starting",
    title_ar: "التخطيط لليوم قبل بدئه",
    title_en: "Plan the Day Before Starting It",
    description_ar: "جلسة قصيرة صباحية لترتيب أولويات اليوم وربطها بالأهداف الأكبر",
    description_en: "A short morning session to organize the day's priorities and link them to bigger goals",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { wisdom: 2, discipline: 2 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 10,
    icon: "🧭",
    tags: ["تخطيط", "صباح", "يومي"],
    motivationalQuotes: [
      "من خطط ليومه، سار بخطى واثقة",
      "دقائق تخطيط توفر ساعات تخبط",
      "اليوم الموجّه أفضل من اليوم العشوائي",
    ],
  },
  {
    id: "work_lessons_learned_log",
    title_ar: "تدوين الدروس المستفادة",
    title_en: "Log Lessons Learned",
    description_ar: "كتابة درس واحد تعلمته من موقف عملي يومي، ناجحًا كان أو صعبًا",
    description_en: "Write down one lesson learned daily from a work situation, whether success or difficulty",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 22,
    statsBoost: { wisdom: 3 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 10,
    icon: "💡",
    tags: ["تأمل", "تعلم", "يومي"],
    motivationalQuotes: [
      "التجربة بلا تأمل، معرفة ضائعة",
      "من دوّن درسه، لم يكرر خطأه",
      "كل موقف يحمل درسًا لمن انتبه له",
    ],
  },
  {
    id: "work_focused_meeting_agenda",
    title_ar: "حضور اجتماع بأجندة واضحة",
    title_en: "Attend Meetings with a Clear Agenda",
    description_ar: "التأكد من وجود أجندة واضحة ونقاط محددة قبل أي اجتماع تحضره أو تقوده",
    description_en: "Ensure a clear agenda and defined points before any meeting you attend or lead",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 25,
    statsBoost: { discipline: 2, influence: 2 },
    frequency: "daily",
    suggestedTime: "afternoon",
    estimatedMinutes: 30,
    icon: "🗂️",
    tags: ["اجتماعات", "تنظيم", "تواصل"],
    motivationalQuotes: [
      "الاجتماع بلا هدف، وقت ضائع للجميع",
      "الوضوح قبل الاجتماع، يوفر وقتًا أثناءه",
      "الأجندة البسيطة تصنع نقاشًا مثمرًا",
    ],
  },
  {
    id: "work_weekly_delegate_task",
    title_ar: "تفويض مهمة واحدة أسبوعيًا",
    title_en: "Delegate One Task Weekly",
    // Custom: يُترك للمستخدم اختيار المهمة والموعد المناسب أسبوعيًا
    description_ar: "تحديد مهمة واحدة أسبوعيًا يمكن تفويضها لتوفير الوقت للأولويات الأهم",
    description_en: "Identify one task weekly that can be delegated to free time for higher priorities",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 26,
    statsBoost: { influence: 3, wisdom: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 15,
    icon: "🤝",
    tags: ["تفويض", "قيادة", "أسبوعي"],
    motivationalQuotes: [
      "من أتقن التفويض، ضاعف وقته",
      "ليس كل عمل يستحق يدك، بعضه يستحق ثقتك بغيرك",
      "القائد الحقيقي يبني قدرات فريقه لا يحتكر المهام",
    ],
  },
  {
    id: "work_weekly_inbox_zero",
    title_ar: "تصفير صندوق الوارد أسبوعيًا",
    title_en: "Weekly Inbox Zero",
    // Custom: يُترك للمستخدم تحديد يوم أسبوعي ثابت لهذه المراجعة الشاملة
    description_ar: "جلسة أسبوعية شاملة لتصفية جميع الرسائل المتراكمة وأرشفتها أو الرد عليها",
    description_en: "A comprehensive weekly session to clear, archive, or respond to all accumulated messages",
    category: "work",
    difficulty: "intermediate",
    minLevel: 15,
    xpReward: 24,
    statsBoost: { discipline: 3 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 30,
    icon: "📭",
    tags: ["بريد", "تنظيم", "أسبوعي"],
    motivationalQuotes: [
      "صندوق فارغ أسبوعيًا، عقل صافٍ باستمرار",
      "التراكم الصغير يوميًا، يصبح جبلاً إن أُهمل أسبوعيًا",
      "نظام أسبوعي بسيط يمنع الفوضى المتراكمة",
    ],
  },

  // ===== Advanced (minLevel 35, xp 35-50) =====
  {
    id: "work_four_hours_deep_work",
    title_ar: "عمل عميق أربع ساعات يوميًا",
    title_en: "Four Hours of Daily Deep Work",
    description_ar: "المحافظة على أربع ساعات يومية من العمل المركّز عالي الجودة",
    description_en: "Maintain four daily hours of focused, high-quality work",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 48,
    statsBoost: { discipline: 5, intelligence: 3 },
    frequency: "daily",
    suggestedTime: "morning",
    estimatedMinutes: 240,
    icon: "🔥",
    tags: ["عمل عميق", "إنتاجية", "متقدم"],
    motivationalQuotes: [
      "أربع ساعات مركّزة، تعادل أسبوعًا من العمل المشتت",
      "القدرة على التركيز الطويل مهارة نادرة تستحق البناء",
      "من امتلك تركيزه، امتلك ناتج عمله",
    ],
  },
  {
    id: "work_daily_content_creation",
    title_ar: "إنشاء محتوى مهني يوميًا",
    title_en: "Daily Professional Content Creation",
    description_ar: "إنتاج محتوى يومي (كتابة، تسجيل، تصميم) يعكس خبرتك المهنية وينشرها",
    description_en: "Produce daily content (writing, recording, design) that shares your professional expertise",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { creativity: 4, influence: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🎬",
    tags: ["محتوى", "إبداع", "يومي"],
    motivationalQuotes: [
      "المحتوى اليومي المتسق يبني حضورًا لا يبنيه محتوى نادر متميز",
      "شارك خبرتك، فربما ينتظرها من لا تعرف",
      "الاستمرارية في النشر، سر بناء الأثر",
    ],
  },
  {
    id: "work_weekly_mentoring",
    title_ar: "توجيه شخص آخر أسبوعيًا",
    title_en: "Weekly Mentoring Session",
    // Custom: يُترك للمستخدم تحديد الشخص والموعد المناسب
    description_ar: "تخصيص جلسة أسبوعية لتوجيه زميل أو شخص أقل خبرة في مجالك",
    description_en: "Dedicate a weekly session to mentoring a colleague or someone less experienced in your field",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { influence: 4, compassion: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🧑‍🏫",
    tags: ["توجيه", "قيادة", "أسبوعي"],
    motivationalQuotes: [
      "من علّم غيره ما يعرف، ضاعف أثره في العالم",
      "التوجيه استثمار في شخص، عائده يمتد لسنوات",
      "القائد الحقيقي يُخرّج قادة آخرين",
    ],
  },
  {
    id: "work_monthly_process_automation",
    title_ar: "أتمتة عملية عمل شهريًا",
    title_en: "Automate One Work Process Monthly",
    // Custom: يُترك للمستخدم تحديد العملية المناسبة كل شهر
    description_ar: "تحديد وأتمتة عملية متكررة واحدة كل شهر لتوفير الوقت والجهد مستقبلاً",
    description_en: "Identify and automate one recurring process each month to save future time and effort",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 45,
    statsBoost: { intelligence: 4, creativity: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "⚙️",
    tags: ["أتمتة", "كفاءة", "شهري"],
    motivationalQuotes: [
      "ما تؤتمته اليوم، يوفر وقتك كل يوم بعده",
      "الكفاءة الحقيقية تعني عملاً أقل لنتيجة أكبر",
      "من حسّن نظامه، ضاعف طاقته دون جهد إضافي",
    ],
  },
  {
    id: "work_weekly_networking",
    title_ar: "بناء شبكة علاقات مهنية أسبوعيًا",
    title_en: "Weekly Professional Networking",
    // Custom: يُترك للمستخدم اختيار الشخص أو الفعالية المناسبة أسبوعيًا
    description_ar: "التواصل مع شخص جديد أو تعزيز علاقة مهنية قائمة كل أسبوع",
    description_en: "Connect with a new person or strengthen an existing professional relationship each week",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 38,
    statsBoost: { influence: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🌐",
    tags: ["شبكة علاقات", "تواصل", "أسبوعي"],
    motivationalQuotes: [
      "شبكة علاقاتك انعكاس لفرصك المستقبلية",
      "علاقة صادقة واحدة، قد تفتح أبوابًا لا تتوقعها",
      "الاستثمار في الناس، استثمار لا يفقد قيمته",
    ],
  },
  {
    id: "work_monthly_performance_review",
    title_ar: "مراجعة الأداء الشهرية",
    title_en: "Monthly Performance Review",
    // Custom: يُترك للمستخدم تحديد يوم ثابت كل شهر لهذه المراجعة الشاملة
    description_ar: "تقييم شامل شهري للأداء المهني، النقاط القوية، ومجالات التحسين",
    description_en: "A comprehensive monthly evaluation of professional performance, strengths, and growth areas",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { wisdom: 4, discipline: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 45,
    icon: "📈",
    tags: ["تقييم", "أداء", "شهري"],
    motivationalQuotes: [
      "من قيّم نفسه بصدق، تجنب مفاجآت الآخرين له",
      "التقدم يُقاس، لا يُفترض",
      "مراجعة شهرية صادقة، بوصلة نحو تطور حقيقي",
    ],
  },
  {
    id: "work_regular_skill_development",
    title_ar: "تطوير مهارة جديدة بانتظام",
    title_en: "Regularly Developing a New Skill",
    description_ar: "تخصيص وقت منتظم لتعلم وممارسة مهارة مهنية جديدة حتى إتقانها",
    description_en: "Dedicate regular time to learning and practicing a new professional skill until mastery",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 44,
    statsBoost: { intelligence: 5 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 30,
    icon: "🛠️",
    tags: ["مهارات", "تطوير", "يومي"],
    motivationalQuotes: [
      "من طوّر نفسه باستمرار، لم يتجاوزه السوق",
      "المهارة الجديدة اليوم، هي ميزتك التنافسية غدًا",
      "الاستثمار في الذات لا ينضب عائده",
    ],
  },
  {
    id: "work_lead_effective_meeting",
    title_ar: "قيادة اجتماع فريق بفعالية",
    title_en: "Leading an Effective Team Meeting",
    description_ar: "قيادة اجتماعات الفريق بوضوح، إدارة الوقت، وضمان مخرجات عملية",
    description_en: "Lead team meetings with clarity, time management, and actionable outcomes",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 42,
    statsBoost: { influence: 5, discipline: 2 },
    frequency: "daily",
    suggestedTime: "afternoon",
    estimatedMinutes: 45,
    icon: "👥",
    tags: ["قيادة", "اجتماعات", "فريق"],
    motivationalQuotes: [
      "القائد الجيد يخرج من الاجتماع بقرارات، لا بأسئلة فقط",
      "إدارة الوقت في الاجتماع احترام لوقت الجميع",
      "من قاد بوضوح، تبعه فريقه بثقة",
    ],
  },
  {
    id: "work_improve_personal_system",
    title_ar: "تحسين نظام العمل الشخصي",
    title_en: "Improving Your Personal Work System",
    description_ar: "مراجعة وتطوير الأدوات والعادات التي تنظّم عملك اليومي بانتظام",
    description_en: "Regularly review and improve the tools and habits that organize your daily work",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 40,
    statsBoost: { wisdom: 3, creativity: 3 },
    frequency: "daily",
    suggestedTime: "evening",
    estimatedMinutes: 15,
    icon: "🧩",
    tags: ["نظام شخصي", "تطوير", "يومي"],
    motivationalQuotes: [
      "النظام الجيد يعمل لصالحك حتى في أيامك الضعيفة",
      "من بنى نظامًا متينًا، اعتمد عليه لا على حماسه فقط",
      "تحسين طفيف يومي، يصنع نظامًا قويًا بمرور الوقت",
    ],
  },
  {
    id: "work_weekly_progress_report",
    title_ar: "كتابة تقرير تقدم أسبوعي",
    title_en: "Writing a Weekly Progress Report",
    // Custom: يُترك للمستخدم تحديد يوم أسبوعي ثابت لكتابة التقرير
    description_ar: "توثيق أسبوعي للإنجازات، التحديات، والخطوات القادمة في مسارك المهني",
    description_en: "A weekly documentation of accomplishments, challenges, and next steps in your career path",
    category: "work",
    difficulty: "advanced",
    minLevel: 35,
    xpReward: 36,
    statsBoost: { wisdom: 3, discipline: 2 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 30,
    icon: "📄",
    tags: ["تقرير", "توثيق", "أسبوعي"],
    motivationalQuotes: [
      "ما لا يُوثّق، يُنسى مع الوقت",
      "التقرير الأسبوعي مرآة صادقة لمسارك",
      "التوثيق المنتظم يحوّل الجهد المتناثر إلى قصة نجاح واضحة",
    ],
  },

  // ===== Expert (minLevel 60, xp 50-80) =====
  {
    id: "work_build_complete_personal_system",
    title_ar: "بناء نظام شخصي متكامل للإنتاجية",
    title_en: "Building a Complete Personal Productivity System",
    // Custom: يُترك للمستخدم تحديد وتيرة مراجعة وتطوير النظام (لا وتيرة ثابتة مناسبة للجميع)
    description_ar: "تصميم وصيانة نظام شامل يربط الأهداف والمهام والعادات في إطار واحد متسق",
    description_en: "Design and maintain a comprehensive system linking goals, tasks, and habits into one coherent framework",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 70,
    statsBoost: { wisdom: 5, discipline: 5 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🏗️",
    tags: ["نظام متكامل", "إنتاجية", "خبير"],
    motivationalQuotes: [
      "النظام المتكامل يحرر طاقتك من التفكير المتكرر إلى الإنجاز الفعلي",
      "من بنى نظامًا يخدمه، لم يعد أسير الفوضى اليومية",
      "الإتقان في الإنتاجية، فن يُصقل لا يُولد جاهزًا",
    ],
  },
  {
    id: "work_teach_lecture_regularly",
    title_ar: "التدريس أو إلقاء محاضرات بانتظام",
    title_en: "Regularly Teaching or Giving Lectures",
    // Custom: يُترك للمستخدم تحديد جهة التدريس والجدول المناسب
    description_ar: "تخصيص وقت منتظم لنقل خبرتك عبر محاضرات أو دورات تدريبية للآخرين",
    description_en: "Dedicate regular time to sharing your expertise through lectures or training sessions",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 65,
    statsBoost: { influence: 6, wisdom: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 90,
    icon: "🎤",
    tags: ["تدريس", "محاضرات", "أثر"],
    motivationalQuotes: [
      "من علّم غيره، ضاعف أثر خبرته في العالم",
      "المعرفة التي تُشارَك، تنمو ولا تنقص",
      "منصة واحدة، قد تُلهم عشرات المسارات المهنية",
    ],
  },
  {
    id: "work_build_community",
    title_ar: "بناء مجتمع مهني",
    title_en: "Building a Professional Community",
    // Custom: يُترك للمستخدم تحديد طبيعة المجتمع ووتيرة الأنشطة
    description_ar: "إنشاء ورعاية مساحة تجمع أشخاصًا يشاركونك مجال اهتمامك المهني",
    description_en: "Create and nurture a space that brings together people sharing your professional interest",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 68,
    statsBoost: { influence: 6, creativity: 3 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🏘️",
    tags: ["مجتمع", "قيادة", "أثر"],
    motivationalQuotes: [
      "المجتمع القوي يبقى بعد أن تغيب أنت عن الساحة",
      "من جمع الناس على هدف مشترك، بنى أثرًا يتضاعف",
      "القيادة الحقيقية تُقاس بمن تُمكّنهم لا بمن يتبعونك فقط",
    ],
  },
  {
    id: "work_build_side_income",
    title_ar: "تأسيس مصدر دخل إضافي",
    title_en: "Establishing an Additional Income Source",
    // Custom: يُترك للمستخدم تحديد طبيعة المشروع ووتيرة العمل عليه
    description_ar: "العمل المنتظم على بناء مصدر دخل مستقل يعزز استقرارك المالي وحريتك المهنية",
    description_en: "Regular work toward building an independent income source that strengthens financial stability",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 72,
    statsBoost: { creativity: 5, discipline: 4 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 60,
    icon: "🌱",
    tags: ["ريادة أعمال", "دخل إضافي", "استقلالية"],
    motivationalQuotes: [
      "البذرة التي تُروى بانتظام، تصبح شجرة تُظلّك يومًا",
      "الاستقلال المالي يبدأ بخطوة صغيرة منتظمة",
      "من بنى مصدرًا إضافيًا، وسّع خياراته لا احتياجاته فقط",
    ],
  },
  {
    id: "work_strategic_project_leadership",
    title_ar: "قيادة استراتيجية لمشروع كبير",
    title_en: "Strategic Leadership of a Major Project",
    description_ar: "توجيه مشروع كبير برؤية استراتيجية واضحة تتجاوز التنفيذ اليومي",
    description_en: "Guide a major project with clear strategic vision beyond day-to-day execution",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { wisdom: 5, influence: 4 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🗺️",
    tags: ["قيادة استراتيجية", "مشاريع", "رؤية"],
    motivationalQuotes: [
      "الرؤية الواضحة تحول فريقًا مشتتًا إلى قوة موحدة",
      "القيادة الاستراتيجية ترى ما بعد المهمة، لا المهمة فقط",
      "من قاد برؤية، لم يضع في التفاصيل اليومية",
    ],
  },
  {
    id: "work_supervise_multi_team",
    title_ar: "الإشراف على فريق متعدد",
    title_en: "Supervising a Multi-Disciplinary Team",
    description_ar: "إدارة وتنسيق فريق متنوع التخصصات نحو أهداف مشتركة بفعالية",
    description_en: "Manage and coordinate a diverse, cross-functional team toward shared goals effectively",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 62,
    statsBoost: { influence: 5, wisdom: 3 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 60,
    icon: "🧑‍💼",
    tags: ["إدارة", "فريق", "تنسيق"],
    motivationalQuotes: [
      "القائد الناجح ينسّق التنوع بدل أن يفرض التماثل",
      "فريق متعدد المهارات، قوة إن أُحسنت قيادته",
      "من أدار بعدل واحترام، كسب ولاء فريقه لا خوفهم فقط",
    ],
  },
  {
    id: "work_publish_book_or_course",
    title_ar: "نشر أثر معرفي (كتاب أو دورة)",
    title_en: "Publishing a Knowledge Legacy (Book or Course)",
    // Custom: يُترك للمستخدم تحديد وتيرة العمل على المشروع طويل المدى
    description_ar: "العمل المنتظم على مشروع معرفي كبير يوثّق خبرتك ويصل لجمهور واسع",
    description_en: "Regular work on a major knowledge project that documents your expertise for a wide audience",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 75,
    statsBoost: { creativity: 5, wisdom: 4 },
    frequency: "custom",
    suggestedTime: "evening",
    estimatedMinutes: 60,
    icon: "📘",
    tags: ["نشر", "كتاب", "أثر طويل"],
    motivationalQuotes: [
      "العمل الذي يُنشر، يبقى أثره بعد أن تنساه أنت",
      "خبرة سنوات، موثّقة في عمل واحد يصل لآلاف",
      "من صبر على مشروع طويل، حصد أثرًا يفوق الجهد اليومي",
    ],
  },
  {
    id: "work_strategic_decision_making",
    title_ar: "اتخاذ قرارات استراتيجية مدروسة",
    title_en: "Making Well-Considered Strategic Decisions",
    description_ar: "المحافظة على منهجية واضحة لاتخاذ القرارات المهمة بعيدًا عن الاستعجال والانفعال",
    description_en: "Maintain a clear methodology for making important decisions, avoiding haste and impulse",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 58,
    statsBoost: { wisdom: 6 },
    frequency: "daily",
    suggestedTime: "anytime",
    estimatedMinutes: 20,
    icon: "⚖️",
    tags: ["قرارات", "استراتيجية", "حكمة"],
    motivationalQuotes: [
      "القرار المتسرع يكلف أضعاف الوقت الذي وفّره",
      "الحكمة في القرار، أهم من السرعة في اتخاذه",
      "من استشار وتأنى، ندم أقل ممن استعجل",
    ],
  },
  {
    id: "work_build_personal_brand",
    title_ar: "بناء علامة شخصية مهنية",
    title_en: "Building a Professional Personal Brand",
    // Custom: يُترك للمستخدم تحديد وتيرة الأنشطة المرتبطة ببناء العلامة
    description_ar: "العمل المستمر على بناء سمعة مهنية واضحة وموثوقة في مجال تخصصك",
    description_en: "Ongoing work to build a clear, trusted professional reputation in your field",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 55,
    statsBoost: { influence: 5, creativity: 2 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 30,
    icon: "🏷️",
    tags: ["علامة شخصية", "سمعة", "أثر"],
    motivationalQuotes: [
      "سمعتك تسبقك قبل أن تتحدث بنفسك",
      "العلامة الشخصية القوية تُبنى بالاتساق لا بالضجيج",
      "من عُرف بصدقه وإتقانه، سبقته سمعته لكل باب",
    ],
  },
  {
    id: "work_invest_in_others_growth",
    title_ar: "الاستثمار في تطوير الآخرين بانتظام",
    title_en: "Regularly Investing in Others' Growth",
    // Custom: يُترك للمستخدم تحديد الأشخاص والوتيرة المناسبة
    description_ar: "تخصيص وقت منتظم لدعم نمو من حولك مهنيًا، لا فقط التركيز على نموك الشخصي",
    description_en: "Dedicate regular time to supporting the professional growth of those around you, not just your own",
    category: "work",
    difficulty: "expert",
    minLevel: 60,
    xpReward: 60,
    statsBoost: { compassion: 4, influence: 4 },
    frequency: "custom",
    suggestedTime: "anytime",
    estimatedMinutes: 45,
    icon: "🌟",
    tags: ["تطوير الآخرين", "قيادة", "أثر"],
    motivationalQuotes: [
      "أعظم القادة يُقاسون بمن رفعوهم معهم",
      "نجاحك يتضاعف حين يصبح نجاح فريقك أيضًا",
      "من استثمر في غيره، بنى إرثًا يفوقه أثرًا",
    ],
  },
];
